services:
  rp_platform:
    container_name: rp_platform
    build: .
    ports:
      - "8787:8787"
      - "3000:3000"
    volumes:
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
