/**
 * Built-in experience SOURCES (canonical single copy).
 *
 * These source bodies back the app-owned built-in experiences: the
 * "Conversation" pair (rules body with manifest id "model_conversation" +
 * the compact messenger visual, turn mode) and the "Catch" pair (rules body
 * with manifest id "catch_arcade" + the arcade visual, REALTIME mode — the
 * wave-6 starter of REALTIME_EXPERIENCE_MODE_PLAN). They live in this
 * zero-dep leaf package — NOT in services/api — because the services/api
 * barrel re-exports the whole server graph (hono/ai-sdk/drizzle), which the
 * frontend cannot import at runtime without breaking its bundle. Both
 * consumers reach one copy here:
 *
 *   - apps/web: the creation-wizard starters (`experience-rules-starters.ts`,
 *     `components/experience/starters/`) re-export these so the editable
 *     starter skeletons and the starter catalog keep resolving against the
 *     same strings — no behavior change.
 *   - services/api: the built-in catalog (`domain/interactive/builtin-experiences`)
 *     imports these as the seed source for the app-owned built-ins.
 *
 * Frozen strings — never mutated. Editing a built-in's source edits it HERE and
 * every consumer sees the change (no drift).
 */

export const CONVERSATION_RULES_SOURCE = [
  "var MAX_MESSAGES = 200;",
  "context.experience.register({",
  "  apiVersion: 1,",
  '  manifest: { id: "model_conversation", name: "Model Conversation" },',
  "  capabilities: [",
  "    { capability: 'participants', reason: 'human and model seats' },",
  "    { capability: 'model', reason: 'AI-driven conversation replies' }",
  "  ],",
  "  create() {",
  "    return { messages: [], turn: 0 };",
  "  },",
  "  project(context) {",
  "    return { messages: context.state.messages.slice(), turn: context.state.turn };",
  "  },",
  "  actions() {",
  "    return [",
  "      { type: 'reply', label: 'Reply', allowsText: true },",
  "      { type: 'finish', label: 'Finish' }",
  "    ];",
  "  },",
  "  reduce(context, action) {",
  "    if (action.type === 'finish') {",
  "      return { state: context.state, status: 'completed', events: [{ visibility: 'public', type: 'finished' }] };",
  "    }",
  "    if (action.type !== 'reply') return { state: context.state, status: 'active', events: [] };",
  "    var text = '';",
  "    if (action.payload && typeof action.payload === 'object') text = action.payload.text || '';",
  "    var participants = context.participants || [];",
  "    var modelSeat = null;",
  "    for (var i = 0; i < participants.length; i++) {",
  "      if (participants[i].controller === 'model') { modelSeat = participants[i]; break; }",
  "    }",
  "    var isModelReply = modelSeat !== null && action.participantId === modelSeat.id;",
  "    var messages = context.state.messages.slice();",
  "    var turn = context.state.turn + 1;",
  "    if (isModelReply) {",
  "      messages.push({ from: 'them', text: text });",
  "      messages = context.helpers.keepLast(messages, MAX_MESSAGES);",
  "      return { state: { messages: messages, turn: turn }, status: 'active', events: [{ visibility: 'public', type: 'model_replied', detail: { text: text } }] };",
  "    }",
  "    messages.push({ from: 'you', text: text });",
  "    messages = context.helpers.keepLast(messages, MAX_MESSAGES);",
  "    var transition = {",
  "      state: { messages: messages, turn: turn },",
  "      status: 'active',",
  "      events: [{ visibility: 'public', type: 'user_replied', detail: { text: text } }]",
  "    };",
  "    if (modelSeat !== null) {",
  "      transition.effects = [{ kind: 'model', request: { viewer: modelSeat.id, mode: 'text', actionType: 'reply', instruction: 'Reply in character to the conversation.' } }];",
  "    }",
  "    return transition;",
  "  }",
  "});",
].join("\n");

export const CONVERSATION_VISUAL_SOURCE = [
  "<style>",
  "  .xp-conv{font:14px/1.4 system-ui,sans-serif;color:#e5e5e5;display:flex;flex-direction:column;width:100%;min-width:300px;max-width:520px;height:420px}",
  "  .xp-conv .history{flex:1;overflow-y:auto;padding:8px;display:flex;flex-direction:column;gap:6px;background:#171717;border-radius:6px}",
  "  .xp-conv .msg{max-width:80%;padding:6px 10px;border-radius:10px;white-space:pre-wrap}",
  "  .xp-conv .msg.them{align-self:flex-start;background:#262626}",
  "  .xp-conv .msg.you{align-self:flex-end;background:#1d4ed8}",
  "  .xp-conv .msg .who{font-size:10px;color:#9ca3af;margin-bottom:2px}",
  "  .xp-conv .typing{color:#9ca3af;font-size:12px;padding:2px 10px;font-style:italic}",
  "  .xp-conv .chatter{color:#9ca3af;font-size:12px;padding:2px 10px;font-style:italic;align-self:flex-start}",
  "  .xp-conv .composer{display:flex;gap:6px;padding:8px 0 0}",
  "  .xp-conv textarea{flex:1;background:#262626;color:#e5e5e5;border:1px solid #404040;border-radius:6px;padding:6px 8px;resize:none;font:inherit}",
  "  .xp-conv button{background:#2563eb;color:#fff;border:none;border-radius:6px;padding:6px 12px;cursor:pointer}",
  "  .xp-conv button:disabled{opacity:.5;cursor:default}",
  "  .xp-conv .finish{background:transparent;color:#fbbf24;border:1px solid #fbbf24}",
  "</style>",
  '<div class="xp-conv" id="xp-root">',
  '  <div class="history" id="xp-history"></div>',
  '  <div class="typing" id="xp-typing" style="display:none">typing...</div>',
  '  <div class="composer">',
  '    <textarea id="xp-input" rows="2" placeholder="Type a reply..."></textarea>',
  '    <button id="xp-send">Send</button>',
  '    <button id="xp-finish" class="finish" style="display:none">Finish</button>',
  '  </div>',
  "</div>",
  "<script>",
  "(function(){",
  "  var root=document.getElementById('xp-root');",
  "  var historyEl=document.getElementById('xp-history');",
  "  var typingEl=document.getElementById('xp-typing');",
  "  var inputEl=document.getElementById('xp-input');",
  "  var sendBtn=document.getElementById('xp-send');",
  "  var finishBtn=document.getElementById('xp-finish');",
  "  var xp;",
  "  function resize(){ if(xp){ xp.resize(root.scrollWidth,root.scrollHeight); } }",
  "  function atBottom(){ historyEl.scrollTop=historyEl.scrollHeight; }",
  "  function hasAction(view,type){ var a=(view&&view.actions)||[]; for(var i=0;i<a.length;i++){if(a[i].type===type)return true;} return false; }",
  "  function render(view){",
  "    var s=(view&&view.state)||{};",
  "    // history",
  "    historyEl.innerHTML='';",
  "    var msgs=s.messages||[];",
  "    for(var i=0;i<msgs.length;i++){(function(m){",
  "      var d=document.createElement('div');d.className='msg '+(m.from==='you'?'you':'them');",
  "      var who=document.createElement('div');who.className='who';who.textContent=m.from;",
  "      d.appendChild(who);",
  "      d.appendChild(document.createTextNode(m.text||''));",
  "      historyEl.appendChild(d);",
  "    })(msgs[i]);}",
  "    // chatter (cosmetic, async flavor item 4): a host-normalized chatter view",
  "    // may ride view.flavor. Rebuilt from scratch every projection: resolved is",
  "    // a history-style bubble, pending a transient placeholder, failed a silent",
  "    // fallback (or nothing). Any other flavor shape renders nothing.",
  "    var flavor=(view&&view.flavor)||null;",
  "    var chatterStatus=(flavor&&typeof flavor==='object'&&typeof flavor.status==='string')?flavor.status:'';",
  "    if(chatterStatus==='resolved'){",
  "      var cd=document.createElement('div');cd.className='msg them';",
  "      var cw=document.createElement('div');cw.className='who';cw.textContent=flavor.seatId||'';",
  "      cd.appendChild(cw);",
  "      cd.appendChild(document.createTextNode(flavor.text||''));",
  "      historyEl.appendChild(cd);",
  "    } else if(chatterStatus==='pending'){",
  "      var cp=document.createElement('div');cp.className='chatter';",
  "      cp.textContent=(flavor.fallback&&typeof flavor.fallback==='string')?flavor.fallback:'…';",
  "      historyEl.appendChild(cp);",
  "    } else if(chatterStatus==='failed'){",
  "      if(flavor.fallback&&typeof flavor.fallback==='string'){",
  "        var cf=document.createElement('div');cf.className='chatter';",
  "        cf.textContent=flavor.fallback;",
  "        historyEl.appendChild(cf);",
  "      }",
  "    }",
  "    atBottom();",
  "    // composer + finish availability",
  "    var canReply=hasAction(view,'reply');",
  "    sendBtn.disabled=!canReply;",
  "    inputEl.disabled=!canReply;",
  "    finishBtn.style.display=hasAction(view,'finish')?'block':'none';",
  "    resize();",
  "  }",
  "  function sendReply(){",
  "    var t=inputEl.value.trim();",
  "    if(!t||!xp) return;",
  "    xp.act('reply',{text:t});",
  "    inputEl.value='';",
  "  }",
  "  sendBtn.onclick=sendReply;",
  "  finishBtn.onclick=function(){ if(xp) xp.finish(); };",
  "  inputEl.addEventListener('keydown',function(e){ if(e.key==='Enter'&&!e.shiftKey){ e.preventDefault(); sendReply(); } });",
  "  xp=window.VibeExperience.connect(render,{",
  "    onPending:function(phase){",
  "      typingEl.style.display=phase==='typing'?'block':'none';",
  "      typingEl.textContent=phase==='typing'?'typing...':(phase==='effect'?'thinking...':'');",
  "    },",
  "    onError:function(err){var d=document.createElement('div');d.className='msg them';d.style.color='#f87171';d.textContent=err.message||err.code;historyEl.appendChild(d);atBottom();}",
  "  });",
  "})();",
  "</script>",
].join("\n");

export const CATCH_RULES_SOURCE = [
  "var PADDLE_Y = 0.84; // paddle line (fraction of field height)",
  "var PADDLE_HALF = 0.07; // half-paddle width (fractions)",
  "var PADDLE_STEP = 0.07; // paddle movement per input nudge (fractions)",
  "var CATCH_WINDOW = 0.16; // one-sided catch radius around the paddle center",
  "var BALL_R = 0.02; // ball radius (fractions)",
  "var MISS_LIMIT = 3; // misses end the round",
  "function spawnBall(context) {",
  "  // Draw ONLY from the deterministic cursor: same seed + same round log",
  "  // must replay the same trajectory. Math.random / Date.now here would make",
  "  // the commit unverifiable (typed 422, nothing applied).",
  "  var r = context.random;",
  "  return { x: 0.2 + r.float() * 0.6, y: 0.04, vx: r.float() * 0.12 - 0.06, vy: 0.16 + r.float() * 0.08 };",
  "}",
  "context.experience.register({",
  "  apiVersion: 1,",
  '  manifest: { id: "catch_arcade", name: "Catch (Realtime)", mode: "realtime", tickMs: 33 },',
  "  capabilities: [",
  "    { capability: 'participants', reason: 'human paddle seat' }",
  "  ],",
  "  create() {",
  "    // State shape: score/misses counters, px = paddle center (x fraction),",
  "    // ball = { x, y, vx, vy } with positions in field fractions and speeds",
  "    // in fractions per second. The first ball falls dead-center with no",
  "    // drift (an immediate catch — a friendly opening beat); every respawn",
  "    // after a catch/miss draws from context.random.",
  "    return {",
  "      score: 0,",
  "      misses: 0,",
  "      px: 0.5,",
  "      ball: { x: 0.5, y: 0.04, vx: 0, vy: 0.2 },",
  "      over: false",
  "    };",
  "  },",
  "  project(context) {",
  "    // Public projection: fractions only — the visual maps them to pixels.",
  "    var b = context.state.ball;",
  "    return { score: context.state.score, misses: context.state.misses, px: context.state.px, ball: { x: b.x, y: b.y }, over: context.state.over };",
  "  },",
  "  actions() {",
  "    // The two legal realtime inputs. The loop legality-checks each before",
  "    // reducing it; a nudge is frame-local with no one-action lock.",
  "    return [ { type: 'left' }, { type: 'right' } ];",
  "  },",
  "  reduce(context, action) {",
  "    // Frame-local input application: a nudge moves the paddle by a fixed",
  "    // step at the next tick boundary (OS key auto-repeat keeps a held key",
  "    // gliding; releasing stops the stream, so the paddle rests).",
  "    var s = context.state;",
  "    var px = s.px;",
  "    if (action.type === 'left') {",
  "      px = Math.max(s.px - PADDLE_STEP, PADDLE_HALF);",
  "    } else if (action.type === 'right') {",
  "      px = Math.min(s.px + PADDLE_STEP, 1 - PADDLE_HALF);",
  "    } else {",
  "      return { state: s, status: 'active', events: [] };",
  "    }",
  "    return { state: { score: s.score, misses: s.misses, px: px, ball: s.ball, over: s.over }, status: 'active', events: [] };",
  "  },",
  "  update(context, dt) {",
  "    // The realtime tick (dt is always the manifest tickMs): the ball falls",
  "    // with constant speed and catch/miss resolve at the paddle line. Keep",
  "    // it cheap — it runs at tick rate.",
  "    var s = context.state;",
  "    var ball = { x: s.ball.x, y: s.ball.y, vx: s.ball.vx, vy: s.ball.vy };",
  "    var dtSec = dt / 1000;",
  "    ball.y += ball.vy * dtSec;",
  "    ball.x += ball.vx * dtSec;",
  "    // Side-wall bounce (the field is 0..1 wide; the ball never leaves).",
  "    if (ball.x - BALL_R < 0) { ball.x = BALL_R; ball.vx = -ball.vx; }",
  "    if (ball.x + BALL_R > 1) { ball.x = 1 - BALL_R; ball.vx = -ball.vx; }",
  "    if (ball.y + BALL_R < PADDLE_Y) {",
  "      return { state: { score: s.score, misses: s.misses, px: s.px, ball: ball, over: s.over }, status: 'active', events: [] };",
  "    }",
  "    // Paddle line reached: inside the catch band is a catch, outside a miss.",
  "    var score = s.score;",
  "    var misses = s.misses;",
  "    if (Math.abs(ball.x - s.px) <= CATCH_WINDOW) {",
  "      score += 1;",
  "    } else {",
  "      misses += 1;",
  "      if (misses >= MISS_LIMIT) {",
  "        return { state: { score: score, misses: misses, px: s.px, ball: ball, over: true }, status: 'completed', events: [] };",
  "      }",
  "    }",
  "    // Respawn from the deterministic cursor (no events/effects — realtime",
  "    // drops them; feedback rides the projected view).",
  "    var next = spawnBall(context);",
  "    return { state: { score: score, misses: misses, px: s.px, ball: next, over: false }, status: 'active', events: [] };",
  "  }",
  "});",
].join("\n");

export const CATCH_VISUAL_SOURCE = [
  "<style>",
  "  .xp-catch{font:14px/1.4 system-ui,sans-serif;color:#e5e5e5;display:flex;flex-direction:column;width:100%;min-width:300px;max-width:520px;height:420px}",
  "  .xp-catch .stage{position:relative;flex:1;background:#171717;border-radius:6px;overflow:hidden}",
  "  .xp-catch canvas{position:absolute;inset:0;width:100%;height:100%}",
  "  .xp-catch .hud{position:absolute;top:8px;left:10px;right:10px;display:flex;justify-content:space-between;align-items:center;color:#9ca3af;font-size:12px;gap:8px}",
  "  .xp-catch .hud .counters{display:flex;gap:14px}",
  "  .xp-catch .end{background:#2563eb;color:#fff;border:none;border-radius:6px;padding:3px 10px;font:inherit;font-size:12px;cursor:pointer}",
  "  .xp-catch .end:hover{background:#1d4ed8}",
  "  .xp-catch .overlay{position:absolute;inset:0;display:none;flex-direction:column;align-items:center;justify-content:center;background:rgba(0,0,0,.72);color:#e5e5e5;text-align:center;gap:4px}",
  "  .xp-catch .overlay h2{margin:0 0 4px;font-size:22px;color:#fbbf24}",
  "  .xp-catch .overlay p{margin:0;color:#d4d4d4}",
  "</style>",
  '  <div class="xp-catch" id="xp-root">',
  '  <div class="stage">',
  '    <canvas id="xp-canvas" width="300" height="420"></canvas>',
  '    <div class="hud"><span class="counters"><span id="xp-score">Score: 0</span><span id="xp-misses">Misses: 0</span></span><button id="xp-end" class="end">End round</button></div>',
  '    <div class="overlay" id="xp-overlay">',
  '      <h2 id="xp-over-title">Round finished</h2>',
  '      <p id="xp-over-body"></p>',
  '    </div>',
  "  </div>",
  "</div>",
  "<script>",
  "(function(){",
  "  var root=document.getElementById('xp-root');",
  "  var cvs=document.getElementById('xp-canvas');",
  "  var scoreEl=document.getElementById('xp-score');",
  "  var missesEl=document.getElementById('xp-misses');",
  "  var endBtn=document.getElementById('xp-end');",
  "  var lastScore=0, lastMisses=0;",
  "  var overlay=document.getElementById('xp-overlay');",
  "  var overTitle=document.getElementById('xp-over-title');",
  "  var overBody=document.getElementById('xp-over-body');",
  "  var xp=null;",
  "  // Logical field is 300x420; the canvas buffer scales by devicePixelRatio",
  "  // (fractions arrive from the rules; mapping happens here, in pixels).",
  "  var W=300, H=420, PADDLE_Y=0.84, PADDLE_HALF=0.07, BALL_R=0.02;",
  "  function resize(){ if(xp){ xp.resize(root.scrollWidth,root.scrollHeight); } }",
  "  function drawField(ctx){ ctx.fillStyle='#171717'; ctx.fillRect(0,0,W,H); }",
  "  function drawPaddle(ctx,px){ ctx.fillStyle='#2563eb'; ctx.fillRect((px-PADDLE_HALF)*W, PADDLE_Y*H-6, PADDLE_HALF*2*W, 6); }",
  "  function drawBall(ctx,ball){ ctx.beginPath(); ctx.arc(ball.x*W, ball.y*H, BALL_R*W, 0, Math.PI*2); ctx.fillStyle='#fbbf24'; ctx.fill(); }",
  "  function renderView(view){",
  "    if(!view) return;",
  "    // Dual-shape: realtime onTick delivers the FLAT project() return",
  "    // ({score,misses,px,ball,over}); the turn-mode host wraps it as",
  "    // {state:...,status:...}. Accept both (same fallback story as",
  "    // act()/actLocal() below) — reading only view.state froze the HUD",
  "    // and ball at their defaults while the round ran underneath.",
  "    var s=(view&&view.state)||view||{};",
  "    // Finished rounds render the terminal card once (turn-mode host pushes",
  "    // status on the view; realtime delivers it via onRoundFinish).",
  "    if((s.over===true)||view.status==='completed'){ showOverlay(view.status||'completed', s.score||0, s.misses||0); return; }",
  "    hideOverlay();",
  "    lastScore=s.score||0;",
  "    lastMisses=s.misses||0;",
  "    scoreEl.textContent='Score: '+lastScore;",
  "    missesEl.textContent='Misses: '+lastMisses;",
  "    var ctx=cvs.getContext&&cvs.getContext('2d');",
  "    if(!ctx) return;",
  "    drawField(ctx);",
  "    drawPaddle(ctx,(typeof s.px==='number')?s.px:0.5);",
  "    var ball=s.ball||{x:0.5,y:0};",
  "    drawBall(ctx,ball);",
  "    resize();",
  "  }",
  "  function hideOverlay(){ overlay.style.display='none'; }",
  "  function showOverlay(status,score,misses){",
  "    overlay.style.display='flex';",
  "    overTitle.textContent=status==='interrupted'?'Round interrupted':'Round finished';",
  "    overBody.textContent='Score: '+score+(status==='completed'?(' / Misses: '+misses):'');",
  "  }",
  "  function handleFinish(f){",
  "    // Realtime terminal claim: score/summary ride the commit; the card",
  "    // renders from the FINAL authoritative state (status + title line).",
  "    var fs=(f&&f.finalState)||{};",
  "    showOverlay((f&&f.status)||'completed', fs.score||0, fs.misses||0);",
  "  }",
  "  function handleError(err){",
  "    // Fatal loop error (e.g. the watchdog): surface it, stop rendering.",
  "    overlay.style.display='flex';",
  "    overTitle.textContent=String('Round error');",
  "    overBody.textContent=String((err&&(err.message||err.kind))||err||'unknown');",
  "    overBody.style.color='#f87171';",
  "  }",
  "  function sendInput(type){",
  "    if(!xp) return;",
  "    // actLocal is the frame-local realtime path (safe in a keydown handler",
  "    // — no round-trip, no one-action lock). Older turn-only hosts fall back",
  "    // to xp.act so the same visual hosts both modes.",
  "    if(typeof xp.actLocal==='function'){ xp.actLocal(type); }",
  "    else if(typeof xp.act==='function'){ xp.act(type); }",
  "  }",
  "  window.addEventListener('keydown',function(e){",
  "    // Input rate is fine: the loop queue is bounded and legality-checked.",
  "    var k=e.key;",
  "    if(k==='ArrowLeft'){ e.preventDefault(); sendInput('left'); }",
  "    else if(k==='ArrowRight'){ e.preventDefault(); sendInput('right'); }",
  "  });",
  "  endBtn.onclick=function(){",
  "    // Deliberate end: score/summary ride the single commit (the loop ends",
  "    // at a tick boundary; without this a skilled player could never finish).",
  "    if(xp&&typeof xp.finishRound==='function'){",
  "      xp.finishRound({ status:'completed', score:lastScore, summary:'Catch: '+lastScore+' caught, '+lastMisses+' missed' });",
  "    }",
  "  };",
  "  // onTick IS the frame (no requestAnimationFrame — the loop drives it).",
  "  xp=window.VibeExperience.connect(renderView,{ onError:handleError });",
  "  if(xp.onTick) xp.onTick(renderView);",
  "  if(xp.onRoundFinish) xp.onRoundFinish(handleFinish);",
  "  if(xp.onRoundError) xp.onRoundError(handleError);",
  "})();",
  "</script>",
].join("\n");
