/**
 * Built-in experience SOURCES (canonical single copy).
 *
 * These source bodies back the app-owned built-in experiences: the
 * "Conversation" pair (rules body with manifest id "model_conversation" +
 * the compact messenger visual, turn mode) and the "Catch" pair (rules body
 * with manifest id "catch_arcade" + the arcade visual, REALTIME mode — the
 * wave-6 starter of REALTIME_EXPERIENCE_MODE_PLAN). They live in this
 * zero-dep leaf package — NOT in services/api — because the services/api
 * barrel re-exports the whole server graph (hono/ai-sdk/drizzle), which the
 * frontend cannot import at runtime without breaking its bundle. Both
 * consumers reach one copy here:
 *
 *   - apps/web: the creation-wizard starters (`experience-rules-starters.ts`,
 *     `components/experience/starters/`) re-export these so the editable
 *     starter skeletons and the starter catalog keep resolving against the
 *     same strings — no behavior change.
 *   - services/api: the built-in catalog (`domain/interactive/builtin-experiences`)
 *     imports these as the seed source for the app-owned built-ins.
 *
 * Frozen strings — never mutated. Editing a built-in's source edits it HERE and
 * every consumer sees the change (no drift).
 */

export const CONVERSATION_RULES_SOURCE = [
  "var MAX_MESSAGES = 200;",
  "context.experience.register({",
  "  apiVersion: 1,",
  '  manifest: { id: "model_conversation", name: "Model Conversation" },',
  "  capabilities: [",
  "    { capability: 'participants', reason: 'human and model seats' },",
  "    { capability: 'model', reason: 'AI-driven conversation replies' }",
  "  ],",
  "  create() {",
  "    return { messages: [], turn: 0 };",
  "  },",
  "  project(context) {",
  "    return { messages: context.state.messages.slice(), turn: context.state.turn };",
  "  },",
  "  actions() {",
  "    return [",
  "      { type: 'reply', label: 'Reply', allowsText: true },",
  "      { type: 'finish', label: 'Finish' }",
  "    ];",
  "  },",
  "  reduce(context, action) {",
  "    if (action.type === 'finish') {",
  "      return { state: context.state, status: 'completed', events: [{ visibility: 'public', type: 'finished' }] };",
  "    }",
  "    if (action.type !== 'reply') return { state: context.state, status: 'active', events: [] };",
  "    var text = '';",
  "    if (action.payload && typeof action.payload === 'object') text = action.payload.text || '';",
  "    var participants = context.participants || [];",
  "    var modelSeat = null;",
  "    for (var i = 0; i < participants.length; i++) {",
  "      if (participants[i].controller === 'model') { modelSeat = participants[i]; break; }",
  "    }",
  "    var isModelReply = modelSeat !== null && action.participantId === modelSeat.id;",
  "    var messages = context.state.messages.slice();",
  "    var turn = context.state.turn + 1;",
  "    if (isModelReply) {",
  "      messages.push({ from: 'them', text: text });",
  "      messages = context.helpers.keepLast(messages, MAX_MESSAGES);",
  "      return { state: { messages: messages, turn: turn }, status: 'active', events: [{ visibility: 'public', type: 'model_replied', detail: { text: text } }] };",
  "    }",
  "    messages.push({ from: 'you', text: text });",
  "    messages = context.helpers.keepLast(messages, MAX_MESSAGES);",
  "    var transition = {",
  "      state: { messages: messages, turn: turn },",
  "      status: 'active',",
  "      events: [{ visibility: 'public', type: 'user_replied', detail: { text: text } }]",
  "    };",
  "    if (modelSeat !== null) {",
  "      transition.effects = [{ kind: 'model', request: { viewer: modelSeat.id, mode: 'text', actionType: 'reply', instruction: 'Reply in character to the conversation.' } }];",
  "    }",
  "    return transition;",
  "  }",
  "});",
].join("\n");

export const CONVERSATION_VISUAL_SOURCE = [
  "<style>",
  "  .xp-conv{font:14px/1.4 system-ui,sans-serif;color:#e5e5e5;display:flex;flex-direction:column;width:100%;min-width:300px;max-width:520px;height:420px}",
  "  .xp-conv .history{flex:1;overflow-y:auto;padding:8px;display:flex;flex-direction:column;gap:6px;background:#171717;border-radius:6px}",
  "  .xp-conv .msg{max-width:80%;padding:6px 10px;border-radius:10px;white-space:pre-wrap}",
  "  .xp-conv .msg.them{align-self:flex-start;background:#262626}",
  "  .xp-conv .msg.you{align-self:flex-end;background:#1d4ed8}",
  "  .xp-conv .msg .who{font-size:10px;color:#9ca3af;margin-bottom:2px}",
  "  .xp-conv .typing{color:#9ca3af;font-size:12px;padding:2px 10px;font-style:italic}",
  "  .xp-conv .chatter{color:#9ca3af;font-size:12px;padding:2px 10px;font-style:italic;align-self:flex-start}",
  "  .xp-conv .composer{display:flex;gap:6px;padding:8px 0 0}",
  "  .xp-conv textarea{flex:1;background:#262626;color:#e5e5e5;border:1px solid #404040;border-radius:6px;padding:6px 8px;resize:none;font:inherit}",
  "  .xp-conv button{background:#2563eb;color:#fff;border:none;border-radius:6px;padding:6px 12px;cursor:pointer}",
  "  .xp-conv button:disabled{opacity:.5;cursor:default}",
  "  .xp-conv .finish{background:transparent;color:#fbbf24;border:1px solid #fbbf24}",
  "</style>",
  '<div class="xp-conv" id="xp-root">',
  '  <div class="history" id="xp-history"></div>',
  '  <div class="typing" id="xp-typing" style="display:none">typing...</div>',
  '  <div class="composer">',
  '    <textarea id="xp-input" rows="2" placeholder="Type a reply..."></textarea>',
  '    <button id="xp-send">Send</button>',
  '    <button id="xp-finish" class="finish" style="display:none">Finish</button>',
  '  </div>',
  "</div>",
  "<script>",
  "(function(){",
  "  var root=document.getElementById('xp-root');",
  "  var historyEl=document.getElementById('xp-history');",
  "  var typingEl=document.getElementById('xp-typing');",
  "  var inputEl=document.getElementById('xp-input');",
  "  var sendBtn=document.getElementById('xp-send');",
  "  var finishBtn=document.getElementById('xp-finish');",
  "  var xp;",
  "  function resize(){ if(xp){ xp.resize(root.scrollWidth,root.scrollHeight); } }",
  "  function atBottom(){ historyEl.scrollTop=historyEl.scrollHeight; }",
  "  function hasAction(view,type){ var a=(view&&view.actions)||[]; for(var i=0;i<a.length;i++){if(a[i].type===type)return true;} return false; }",
  "  function render(view){",
  "    var s=(view&&view.state)||{};",
  "    // history",
  "    historyEl.innerHTML='';",
  "    var msgs=s.messages||[];",
  "    for(var i=0;i<msgs.length;i++){(function(m){",
  "      var d=document.createElement('div');d.className='msg '+(m.from==='you'?'you':'them');",
  "      var who=document.createElement('div');who.className='who';who.textContent=m.from;",
  "      d.appendChild(who);",
  "      d.appendChild(document.createTextNode(m.text||''));",
  "      historyEl.appendChild(d);",
  "    })(msgs[i]);}",
  "    // chatter (cosmetic, async flavor item 4): a host-normalized chatter view",
  "    // may ride view.flavor. Rebuilt from scratch every projection: resolved is",
  "    // a history-style bubble, pending a transient placeholder, failed a silent",
  "    // fallback (or nothing). Any other flavor shape renders nothing.",
  "    var flavor=(view&&view.flavor)||null;",
  "    var chatterStatus=(flavor&&typeof flavor==='object'&&typeof flavor.status==='string')?flavor.status:'';",
  "    if(chatterStatus==='resolved'){",
  "      var cd=document.createElement('div');cd.className='msg them';",
  "      var cw=document.createElement('div');cw.className='who';cw.textContent=flavor.seatId||'';",
  "      cd.appendChild(cw);",
  "      cd.appendChild(document.createTextNode(flavor.text||''));",
  "      historyEl.appendChild(cd);",
  "    } else if(chatterStatus==='pending'){",
  "      var cp=document.createElement('div');cp.className='chatter';",
  "      cp.textContent=(flavor.fallback&&typeof flavor.fallback==='string')?flavor.fallback:'…';",
  "      historyEl.appendChild(cp);",
  "    } else if(chatterStatus==='failed'){",
  "      if(flavor.fallback&&typeof flavor.fallback==='string'){",
  "        var cf=document.createElement('div');cf.className='chatter';",
  "        cf.textContent=flavor.fallback;",
  "        historyEl.appendChild(cf);",
  "      }",
  "    }",
  "    atBottom();",
  "    // composer + finish availability",
  "    var canReply=hasAction(view,'reply');",
  "    sendBtn.disabled=!canReply;",
  "    inputEl.disabled=!canReply;",
  "    finishBtn.style.display=hasAction(view,'finish')?'block':'none';",
  "    resize();",
  "  }",
  "  function sendReply(){",
  "    var t=inputEl.value.trim();",
  "    if(!t||!xp) return;",
  "    xp.act('reply',{text:t});",
  "    inputEl.value='';",
  "  }",
  "  sendBtn.onclick=sendReply;",
  "  finishBtn.onclick=function(){ if(xp) xp.finish(); };",
  "  inputEl.addEventListener('keydown',function(e){ if(e.key==='Enter'&&!e.shiftKey){ e.preventDefault(); sendReply(); } });",
  "  xp=window.VibeExperience.connect(render,{",
  "    onPending:function(phase){",
  "      typingEl.style.display=phase==='typing'?'block':'none';",
  "      typingEl.textContent=phase==='typing'?'typing...':(phase==='effect'?'thinking...':'');",
  "    },",
  "    onError:function(err){var d=document.createElement('div');d.className='msg them';d.style.color='#f87171';d.textContent=err.message||err.code;historyEl.appendChild(d);atBottom();}",
  "  });",
  "})();",
  "</script>",
].join("\n");

export const BREAKOUT_RULES_SOURCE = [
  "var PADDLE_Y = 0.9; // paddle line (fraction of field height)",
  "var PADDLE_HALF = 0.09; // half-paddle width (fractions)",
  "var PADDLE_STEP = 0.06; // paddle movement per input nudge (fractions)",
  "var BALL_R = 0.014; // ball radius (fractions)",
  "var LIVES = 3; // balls per round",
  "var COLS = 8, ROWS = 4; // brick field",
  "var FIELD_LEFT = 0.06, FIELD_RIGHT = 0.94;",
  "var FIELD_TOP = 0.08, ROW_H = 0.055;",
  "var COL_W = (FIELD_RIGHT - FIELD_LEFT) / COLS;",
  "var ROW_SCORES = [7, 5, 3, 1]; // top row pays most (classic Breakout)",
  "var SPEED_BASE = 0.5; // ball speed (fractions per second)",
  "var SPEED_PER_BALL = 0.07; // each lost ball makes the next one faster",
  "var MAX_BOUNCE = 0.8; // max |vx| as a share of speed off the paddle",
  "var FULL_FIELD = 0xFFFFFFFF; // 32 alive bricks, bit = row * COLS + col",
  "function speedFor(lost) { return SPEED_BASE + SPEED_PER_BALL * lost; }",
  "function clampBounce(off) {",
  "  if (off > MAX_BOUNCE) return MAX_BOUNCE;",
  "  if (off < -MAX_BOUNCE) return -MAX_BOUNCE;",
  "  return off;",
  "}",
  "function launchBall(context, px, lost) {",
  "  // Respawn launch: draw the horizontal share from the deterministic",
  "  // cursor ONLY (same seed + same round log must replay the same",
  "  // trajectory — Math.random / Date.now would make the commit",
  "  // unverifiable, typed 422, nothing applied).",
  "  var r = context.random;",
  "  var speed = speedFor(lost);",
  "  var vx = (r.float() * 0.7 - 0.35) * speed;",
  "  return { x: px, y: PADDLE_Y - BALL_R - 0.01, vx: vx, vy: -Math.sqrt(speed * speed - vx * vx) };",
  "}",
  "context.experience.register({",
  "  apiVersion: 1,",
  '  manifest: { id: "breakout_arcade", name: "Breakout (Realtime)", mode: "realtime", tickMs: 33 },',
  "  capabilities: [",
  "    { capability: 'participants', reason: 'human paddle seat' }",
  "  ],",
  "  create() {",
  "    // State shape: score counter, lives (balls left), px = paddle center",
  "    // (x fraction), ball = { x, y, vx, vy } with positions in field",
  "    // fractions and speeds in fractions per second, bricks = alive mask",
  "    // (bit = row * COLS + col; bitwise ops keep it int32). The opening",
  "    // launch is FIXED (no cursor draws) — a friendly center break, the",
  "    // same story the Catch starter opened with.",
  "    var sp = speedFor(0);",
  "    var vx0 = 0.12 * sp;",
  "    return {",
  "      score: 0,",
  "      lives: LIVES,",
  "      px: 0.5,",
  "      ball: { x: 0.5, y: PADDLE_Y - BALL_R - 0.02, vx: vx0, vy: -Math.sqrt(sp * sp - vx0 * vx0) },",
  "      bricks: FULL_FIELD,",
  "      over: false,",
  "      won: false",
  "    };",
  "  },",
  "  project(context) {",
  "    // Public projection: fractions + the raw brick mask — the visual maps",
  "    // them to pixels and colors. The ball direction stays hidden (position",
  "    // only), exactly like the Catch projection.",
  "    var s = context.state;",
  "    var b = s.ball;",
  "    return { score: s.score, lives: s.lives, px: s.px, ball: { x: b.x, y: b.y }, bricks: s.bricks, over: s.over, won: s.won };",
  "  },",
  "  actions() {",
  "    // The two legal realtime inputs (unchanged from Catch): frame-local",
  "    // nudges, legality-checked by the loop before each reduce.",
  "    return [ { type: 'left' }, { type: 'right' } ];",
  "  },",
  "  reduce(context, action) {",
  "    // Frame-local input application: a nudge moves the paddle by a fixed",
  "    // step at the next tick boundary (OS key auto-repeat keeps a held key",
  "    // gliding; releasing stops the stream, so the paddle rests).",
  "    var s = context.state;",
  "    var px = s.px;",
  "    if (action.type === 'left') {",
  "      px = Math.max(s.px - PADDLE_STEP, PADDLE_HALF);",
  "    } else if (action.type === 'right') {",
  "      px = Math.min(s.px + PADDLE_STEP, 1 - PADDLE_HALF);",
  "    } else {",
  "      return { state: s, status: 'active', events: [] };",
  "    }",
  "    return { state: { score: s.score, lives: s.lives, px: px, ball: s.ball, bricks: s.bricks, over: s.over, won: s.won }, status: 'active', events: [] };",
  "  },",
  "  update(context, dt) {",
  "    // The realtime tick (dt is always the manifest tickMs): integrate the",
  "    // ball, bounce it off the walls / the paddle (angle from the hit",
  "    // offset) / bricks (reflect on the axis of least penetration), and end",
  "    // the round on a cleared field (win) or the last lost ball (loss).",
  "    // Keep it cheap — it runs at tick rate.",
  "    var s = context.state;",
  "    if (s.over) { return { state: s, status: 'completed', events: [] }; }",
  "    var dtSec = dt / 1000;",
  "    var ball = { x: s.ball.x + s.ball.vx * dtSec, y: s.ball.y + s.ball.vy * dtSec, vx: s.ball.vx, vy: s.ball.vy };",
  "    var score = s.score;",
  "    var lives = s.lives;",
  "    var bricks = s.bricks;",
  "    // Side and top walls (the field is 0..1 wide; the bottom is NOT a",
  "    // wall — falling past the paddle loses the ball).",
  "    if (ball.x - BALL_R < 0) { ball.x = BALL_R; ball.vx = Math.abs(ball.vx); }",
  "    if (ball.x + BALL_R > 1) { ball.x = 1 - BALL_R; ball.vx = -Math.abs(ball.vx); }",
  "    if (ball.y - BALL_R < 0) { ball.y = BALL_R; ball.vy = Math.abs(ball.vy); }",
  "    // Paddle bounce: where the ball lands on the paddle sets the outgoing",
  "    // angle (edge hits fly wide, center hits climb straight) — the entire",
  "    // skill of Breakout. The vertical share is derived so the speed stays",
  "    // constant. The upper bound on ball.y stops a ball that is already",
  "    // UNDER the paddle from bouncing back up out of a miss.",
  "    if (ball.vy > 0 && ball.y + BALL_R >= PADDLE_Y && ball.y + BALL_R < PADDLE_Y + 0.05 && Math.abs(ball.x - s.px) <= PADDLE_HALF + BALL_R) {",
  "      var lost = LIVES - lives;",
  "      var speed = speedFor(lost);",
  "      var off = clampBounce((ball.x - s.px) / PADDLE_HALF);",
  "      ball.vx = off * speed;",
  "      ball.vy = -Math.sqrt(speed * speed - ball.vx * ball.vx);",
  "      ball.y = PADDLE_Y - BALL_R;",
  "    }",
  "    // Brick field: test the ball center's cell (one brick per tick max —",
  "    // plenty at tick rate). The bit layout mirrors the visual decode.",
  "    if (ball.x >= FIELD_LEFT && ball.x <= FIELD_RIGHT && ball.y >= FIELD_TOP && ball.y <= FIELD_TOP + ROWS * ROW_H) {",
  "      var col = Math.floor((ball.x - FIELD_LEFT) / COL_W);",
  "      var row = Math.floor((ball.y - FIELD_TOP) / ROW_H);",
  "      var bit = 1 << (row * COLS + col);",
  "      if (bricks & bit) {",
  "        bricks = bricks & ~bit;",
  "        score += ROW_SCORES[row];",
  "        // Reflect on the axis of least penetration into the hit cell, so",
  "        // a ball clipping a brick side turns horizontally instead of",
  "        // tunnelling through the row.",
  "        var cx0 = FIELD_LEFT + col * COL_W;",
  "        var cy0 = FIELD_TOP + row * ROW_H;",
  "        var minX = Math.min(ball.x - cx0, cx0 + COL_W - ball.x);",
  "        var minY = Math.min(ball.y - cy0, cy0 + ROW_H - ball.y);",
  "        if (minX < minY) {",
  "          ball.vx = (ball.x - cx0 < cx0 + COL_W - ball.x) ? -Math.abs(ball.vx) : Math.abs(ball.vx);",
  "        } else {",
  "          ball.vy = (ball.y - cy0 < cy0 + ROW_H - ball.y) ? -Math.abs(ball.vy) : Math.abs(ball.vy);",
  "        }",
  "        if (bricks === 0) {",
  "          return { state: { score: score, lives: lives, px: s.px, ball: ball, bricks: 0, over: true, won: true }, status: 'completed', events: [] };",
  "        }",
  "      }",
  "    }",
  "    // Bottom: ball lost. The respawn launch draws from the cursor.",
  "    if (ball.y - BALL_R > 1) {",
  "      lives -= 1;",
  "      if (lives <= 0) {",
  "        return { state: { score: score, lives: 0, px: s.px, ball: ball, bricks: bricks, over: true, won: false }, status: 'completed', events: [] };",
  "      }",
  "      ball = launchBall(context, s.px, LIVES - lives);",
  "    }",
  "    // No events/effects — realtime drops them; feedback rides the",
  "    // projected view.",
  "    return { state: { score: score, lives: lives, px: s.px, ball: ball, bricks: bricks, over: false, won: false }, status: 'active', events: [] };",
  "  }",
  "});",
].join("\n");

export const BREAKOUT_VISUAL_SOURCE = [
  "<style>",
  "  .xp-brk{font:14px/1.4 system-ui,sans-serif;color:#e5e5e5;display:flex;flex-direction:column;width:100%;min-width:300px;max-width:520px;height:420px}",
  "  .xp-brk .stage{position:relative;flex:1;background:#0b0e14;border:1px solid #1e293b;border-radius:6px;overflow:hidden}",
  "  .xp-brk canvas{position:absolute;inset:0;width:100%;height:100%}",
  "  .xp-brk .hud{position:absolute;top:8px;left:10px;right:10px;display:flex;justify-content:space-between;align-items:center;color:#94a3b8;font-size:12px;gap:8px}",
  "  .xp-brk .hud .counters{display:flex;gap:14px;align-items:center}",
  "  .xp-brk .hud .balls{color:#fbbf24;letter-spacing:3px;font-size:10px;line-height:1}",
  "  .xp-brk .end{background:#2563eb;color:#fff;border:none;border-radius:6px;padding:3px 10px;font:inherit;font-size:12px;cursor:pointer}",
  "  .xp-brk .end:hover{background:#1d4ed8}",
  "  .xp-brk .overlay{position:absolute;inset:0;display:none;flex-direction:column;align-items:center;justify-content:center;background:rgba(0,0,0,.72);color:#e5e5e5;text-align:center;gap:4px}",
  "  .xp-brk .overlay h2{margin:0 0 4px;font-size:22px;color:#fbbf24}",
  "  .xp-brk .overlay p{margin:0;color:#d4d4d4}",
  "</style>",
  '  <div class="xp-brk" id="xp-root">',
  '  <div class="stage">',
  '    <canvas id="xp-canvas" width="300" height="420"></canvas>',
  '    <div class="hud"><span class="counters"><span id="xp-score">Score: 0</span><span id="xp-lives" class="balls">●●●</span></span><button id="xp-end" class="end">End round</button></div>',
  '    <div class="overlay" id="xp-overlay">',
  '      <h2 id="xp-over-title">Round finished</h2>',
  '      <p id="xp-over-body"></p>',
  '    </div>',
  "  </div>",
  "</div>",
  "<script>",
  "(function(){",
  "  var root=document.getElementById('xp-root');",
  "  var cvs=document.getElementById('xp-canvas');",
  "  var scoreEl=document.getElementById('xp-score');",
  "  var livesEl=document.getElementById('xp-lives');",
  "  var endBtn=document.getElementById('xp-end');",
  "  var lastScore=0;",
  "  var overlay=document.getElementById('xp-overlay');",
  "  var overTitle=document.getElementById('xp-over-title');",
  "  var overBody=document.getElementById('xp-over-body');",
  "  var xp=null;",
  "  // Logical field is 300x420; the canvas buffer scales by devicePixelRatio",
  "  // (fractions arrive from the rules; mapping happens here, in pixels).",
  "  // The brick constants mirror the rules bit layout: bit = row * COLS + col.",
  "  var W=300, H=420;",
  "  var PADDLE_Y=0.9, PADDLE_HALF=0.09, BALL_R=0.014;",
  "  var COLS=8, ROWS=4, FIELD_LEFT=0.06, FIELD_RIGHT=0.94, FIELD_TOP=0.08, ROW_H=0.055;",
  "  var COL_W=(FIELD_RIGHT-FIELD_LEFT)/COLS;",
  "  var ROW_COLORS=['#f87171','#fbbf24','#34d399','#60a5fa'];",
  "  var trail=[];",
  "  function resize(){ if(xp){ xp.resize(root.scrollWidth,root.scrollHeight); } }",
  "  function drawField(ctx){",
  "    var g=ctx.createLinearGradient(0,0,0,H);",
  "    g.addColorStop(0,'#0d1220'); g.addColorStop(1,'#0b0e14');",
  "    ctx.fillStyle=g; ctx.fillRect(0,0,W,H);",
  "  }",
  "  function drawBricks(ctx,mask){",
  "    if(typeof mask!=='number') return;",
  "    for(var r=0;r<ROWS;r++){ for(var c=0;c<COLS;c++){",
  "      if(((mask>>>(r*COLS+c))&1)===0) continue;",
  "      var col=ROW_COLORS[r];",
  "      var x=(FIELD_LEFT+c*COL_W+0.006)*W, y=(FIELD_TOP+r*ROW_H+0.007)*H;",
  "      var w=(COL_W-0.012)*W, h=(ROW_H-0.014)*H;",
  "      ctx.shadowColor=col; ctx.shadowBlur=7;",
  "      ctx.fillStyle=col; ctx.fillRect(x,y,w,h);",
  "    }}",
  "    ctx.shadowBlur=0;",
  "  }",
  "  function drawPaddle(ctx,px){",
  "    var x=(px-PADDLE_HALF)*W, y=PADDLE_Y*H-6, w=PADDLE_HALF*2*W;",
  "    var g=ctx.createLinearGradient(x,0,x+w,0);",
  "    g.addColorStop(0,'#60a5fa'); g.addColorStop(0.5,'#e2e8f0'); g.addColorStop(1,'#60a5fa');",
  "    ctx.shadowColor='#60a5fa'; ctx.shadowBlur=10;",
  "    ctx.fillStyle=g;",
  "    ctx.beginPath();",
  "    if(ctx.roundRect){ ctx.roundRect(x,y,w,7,4); } else { ctx.rect(x,y,w,7); }",
  "    ctx.fill();",
  "    ctx.shadowBlur=0;",
  "  }",
  "  function drawBall(ctx,ball){",
  "    // Short fading trail: purely cosmetic, visual-local state (never sent",
  "    // back to the rules).",
  "    trail.push({x:ball.x,y:ball.y});",
  "    if(trail.length>7) trail.shift();",
  "    for(var i=0;i<trail.length-1;i++){",
  "      var a=(i+1)/trail.length;",
  "      ctx.beginPath(); ctx.arc(trail[i].x*W,trail[i].y*H,BALL_R*W*a,0,Math.PI*2);",
  "      ctx.fillStyle='rgba(251,191,36,'+(0.10*a).toFixed(3)+')'; ctx.fill();",
  "    }",
  "    ctx.shadowColor='#fbbf24'; ctx.shadowBlur=12;",
  "    ctx.beginPath(); ctx.arc(ball.x*W,ball.y*H,BALL_R*W,0,Math.PI*2);",
  "    ctx.fillStyle='#fbbf24'; ctx.fill();",
  "    ctx.shadowBlur=0;",
  "  }",
  "  function renderView(view){",
  "    if(!view) return;",
  "    // Dual-shape: realtime onTick delivers the FLAT project() return",
  "    // ({score,lives,px,ball,bricks,over,won}); the turn-mode host wraps it",
  "    // as {state:...}. Accept both (RM-12d: reading only view.state froze",
  "    // the HUD at defaults while the round ran underneath).",
  "    var s=(view&&view.state)||view||{};",
  "    // Finished rounds render the terminal card once (turn-mode host pushes",
  "    // status on the view; realtime delivers it via onRoundFinish).",
  "    if((s.over===true)||view.status==='completed'){ showOverlay(view.status||'completed',s); return; }",
  "    hideOverlay();",
  "    lastScore=s.score||0;",
  "    scoreEl.textContent='Score: '+lastScore;",
  "    var balls=(typeof s.lives==='number')?s.lives:3;",
  "    livesEl.textContent=new Array(balls+1).join('●');",
  "    var ctx=cvs.getContext&&cvs.getContext('2d');",
  "    if(!ctx) return;",
  "    drawField(ctx);",
  "    drawBricks(ctx,(typeof s.bricks==='number')?s.bricks:-1);",
  "    drawPaddle(ctx,(typeof s.px==='number')?s.px:0.5);",
  "    drawBall(ctx,s.ball||{x:0.5,y:0.5});",
  "    resize();",
  "  }",
  "  function bricksLeft(mask){ var n=0; for(var i=0;i<32;i++){ if(((mask>>>i)&1)===1) n++; } return n; }",
  "  function hideOverlay(){ overlay.style.display='none'; }",
  "  function showOverlay(status,s){",
  "    overlay.style.display='flex';",
  "    var won=(s&&s.won===true);",
  "    overTitle.textContent=won?'Field cleared!':(status==='interrupted'?'Round interrupted':'Round finished');",
  "    var body='Score: '+((s&&s.score)||0);",
  "    if(!won&&s&&typeof s.bricks==='number'){ body+=' / Bricks left: '+bricksLeft(s.bricks); }",
  "    overBody.textContent=body;",
  "  }",
  "  function handleFinish(f){",
  "    // Realtime terminal claim: score/summary ride the commit; the card",
  "    // renders from the FINAL authoritative state (status + title line).",
  "    var fs=(f&&f.finalState)||{};",
  "    showOverlay((f&&f.status)||'completed',fs);",
  "  }",
  "  function handleError(err){",
  "    // Fatal loop error (e.g. the watchdog): surface it, stop rendering.",
  "    overlay.style.display='flex';",
  "    overTitle.textContent=String('Round error');",
  "    overBody.textContent=String((err&&(err.message||err.kind))||err||'unknown');",
  "    overBody.style.color='#f87171';",
  "  }",
  "  function sendInput(type){",
  "    if(!xp) return;",
  "    // actLocal is the frame-local realtime path (safe in a keydown handler",
  "    // — no round-trip, no one-action lock). Older turn-only hosts fall back",
  "    // to xp.act so the same visual hosts both modes.",
  "    if(typeof xp.actLocal==='function'){ xp.actLocal(type); }",
  "    else if(typeof xp.act==='function'){ xp.act(type); }",
  "  }",
  "  window.addEventListener('keydown',function(e){",
  "    // Input rate is fine: the loop queue is bounded and legality-checked.",
  "    var k=e.key;",
  "    if(k==='ArrowLeft'){ e.preventDefault(); sendInput('left'); }",
  "    else if(k==='ArrowRight'){ e.preventDefault(); sendInput('right'); }",
  "  });",
  "  endBtn.onclick=function(){",
  "    // Deliberate end: score/summary ride the single commit (the loop ends",
  "    // at a tick boundary; without this a slow clear could never finish).",
  "    if(xp&&typeof xp.finishRound==='function'){",
  "      xp.finishRound({ status:'completed', score:lastScore, summary:'Breakout: '+lastScore+' points' });",
  "    }",
  "  };",
  "  // onTick IS the frame (no requestAnimationFrame — the loop drives it).",
  "  xp=window.VibeExperience.connect(renderView,{ onError:handleError });",
  "  if(xp.onTick) xp.onTick(renderView);",
  "  if(xp.onRoundFinish) xp.onRoundFinish(handleFinish);",
  "  if(xp.onRoundError) xp.onRoundError(handleError);",
  "})();",
  "</script>",
].join("\n");
