/**
 * Built-in experience SOURCES (canonical single copy).
 *
 * These two source bodies back the "Conversation" built-in experience: the
 * rules body is the interactive script (manifest id "model_conversation"), the
 * visual body is the compact messenger visual. They live in this zero-dep leaf
 * package — NOT in services/api — because the services/api barrel re-exports the
 * whole server graph (hono/ai-sdk/drizzle), which the frontend cannot import at
 * runtime without breaking its bundle. Both consumers reach one copy here:
 *
 *   - apps/web: the creation-wizard starters (`experience-rules-starters.ts`,
 *     `starters/conversation.ts`) re-export these so the editable starter
 *     skeletons and the IR-90B parity suite keep resolving against the same
 *     strings — no behavior change.
 *   - services/api: the built-in catalog (`domain/interactive/builtin-experiences`)
 *     imports these as the seed source for the app-owned "Conversation" built-in.
 *
 * Frozen strings — never mutated. Editing a built-in's source edits it HERE and
 * every consumer sees the change (no drift).
 */

export const CONVERSATION_RULES_SOURCE = [
  "var MAX_MESSAGES = 200;",
  "context.experience.register({",
  "  apiVersion: 1,",
  '  manifest: { id: "model_conversation", name: "Model Conversation" },',
  "  capabilities: [",
  "    { capability: 'participants', reason: 'human and model seats' },",
  "    { capability: 'model', reason: 'AI-driven conversation replies' }",
  "  ],",
  "  create() {",
  "    return { messages: [], turn: 0 };",
  "  },",
  "  project(context) {",
  "    return { messages: context.state.messages.slice(), turn: context.state.turn };",
  "  },",
  "  actions() {",
  "    return [",
  "      { type: 'reply', label: 'Reply', allowsText: true },",
  "      { type: 'finish', label: 'Finish' }",
  "    ];",
  "  },",
  "  reduce(context, action) {",
  "    if (action.type === 'finish') {",
  "      return { state: context.state, status: 'completed', events: [{ visibility: 'public', type: 'finished' }] };",
  "    }",
  "    if (action.type !== 'reply') return { state: context.state, status: 'active', events: [] };",
  "    var text = '';",
  "    if (action.payload && typeof action.payload === 'object') text = action.payload.text || '';",
  "    var participants = context.participants || [];",
  "    var modelSeat = null;",
  "    for (var i = 0; i < participants.length; i++) {",
  "      if (participants[i].controller === 'model') { modelSeat = participants[i]; break; }",
  "    }",
  "    var isModelReply = modelSeat !== null && action.participantId === modelSeat.id;",
  "    var messages = context.state.messages.slice();",
  "    var turn = context.state.turn + 1;",
  "    if (isModelReply) {",
  "      messages.push({ from: 'them', text: text });",
  "      messages = context.helpers.keepLast(messages, MAX_MESSAGES);",
  "      return { state: { messages: messages, turn: turn }, status: 'active', events: [{ visibility: 'public', type: 'model_replied', detail: { text: text } }] };",
  "    }",
  "    messages.push({ from: 'you', text: text });",
  "    messages = context.helpers.keepLast(messages, MAX_MESSAGES);",
  "    var transition = {",
  "      state: { messages: messages, turn: turn },",
  "      status: 'active',",
  "      events: [{ visibility: 'public', type: 'user_replied', detail: { text: text } }]",
  "    };",
  "    if (modelSeat !== null) {",
  "      transition.effects = [{ kind: 'model', request: { viewer: modelSeat.id, mode: 'text', actionType: 'reply', instruction: 'Reply in character to the conversation.' } }];",
  "    }",
  "    return transition;",
  "  }",
  "});",
].join("\n");

export const CONVERSATION_VISUAL_SOURCE = [
  "<style>",
  "  .xp-conv{font:14px/1.4 system-ui,sans-serif;color:#e5e5e5;display:flex;flex-direction:column;width:100%;min-width:300px;max-width:520px;height:420px}",
  "  .xp-conv .history{flex:1;overflow-y:auto;padding:8px;display:flex;flex-direction:column;gap:6px;background:#171717;border-radius:6px}",
  "  .xp-conv .msg{max-width:80%;padding:6px 10px;border-radius:10px;white-space:pre-wrap}",
  "  .xp-conv .msg.them{align-self:flex-start;background:#262626}",
  "  .xp-conv .msg.you{align-self:flex-end;background:#1d4ed8}",
  "  .xp-conv .msg .who{font-size:10px;color:#9ca3af;margin-bottom:2px}",
  "  .xp-conv .typing{color:#9ca3af;font-size:12px;padding:2px 10px;font-style:italic}",
  "  .xp-conv .chatter{color:#9ca3af;font-size:12px;padding:2px 10px;font-style:italic;align-self:flex-start}",
  "  .xp-conv .composer{display:flex;gap:6px;padding:8px 0 0}",
  "  .xp-conv textarea{flex:1;background:#262626;color:#e5e5e5;border:1px solid #404040;border-radius:6px;padding:6px 8px;resize:none;font:inherit}",
  "  .xp-conv button{background:#2563eb;color:#fff;border:none;border-radius:6px;padding:6px 12px;cursor:pointer}",
  "  .xp-conv button:disabled{opacity:.5;cursor:default}",
  "  .xp-conv .finish{background:transparent;color:#fbbf24;border:1px solid #fbbf24}",
  "</style>",
  '<div class="xp-conv" id="xp-root">',
  '  <div class="history" id="xp-history"></div>',
  '  <div class="typing" id="xp-typing" style="display:none">typing...</div>',
  '  <div class="composer">',
  '    <textarea id="xp-input" rows="2" placeholder="Type a reply..."></textarea>',
  '    <button id="xp-send">Send</button>',
  '    <button id="xp-finish" class="finish" style="display:none">Finish</button>',
  '  </div>',
  "</div>",
  "<script>",
  "(function(){",
  "  var root=document.getElementById('xp-root');",
  "  var historyEl=document.getElementById('xp-history');",
  "  var typingEl=document.getElementById('xp-typing');",
  "  var inputEl=document.getElementById('xp-input');",
  "  var sendBtn=document.getElementById('xp-send');",
  "  var finishBtn=document.getElementById('xp-finish');",
  "  var xp;",
  "  function resize(){ if(xp){ xp.resize(root.scrollWidth,root.scrollHeight); } }",
  "  function atBottom(){ historyEl.scrollTop=historyEl.scrollHeight; }",
  "  function hasAction(view,type){ var a=(view&&view.actions)||[]; for(var i=0;i<a.length;i++){if(a[i].type===type)return true;} return false; }",
  "  function render(view){",
  "    var s=(view&&view.state)||{};",
  "    // history",
  "    historyEl.innerHTML='';",
  "    var msgs=s.messages||[];",
  "    for(var i=0;i<msgs.length;i++){(function(m){",
  "      var d=document.createElement('div');d.className='msg '+(m.from==='you'?'you':'them');",
  "      var who=document.createElement('div');who.className='who';who.textContent=m.from;",
  "      d.appendChild(who);",
  "      d.appendChild(document.createTextNode(m.text||''));",
  "      historyEl.appendChild(d);",
  "    })(msgs[i]);}",
  "    // chatter (cosmetic, async flavor item 4): a host-normalized chatter view",
  "    // may ride view.flavor. Rebuilt from scratch every projection: resolved is",
  "    // a history-style bubble, pending a transient placeholder, failed a silent",
  "    // fallback (or nothing). Any other flavor shape renders nothing.",
  "    var flavor=(view&&view.flavor)||null;",
  "    var chatterStatus=(flavor&&typeof flavor==='object'&&typeof flavor.status==='string')?flavor.status:'';",
  "    if(chatterStatus==='resolved'){",
  "      var cd=document.createElement('div');cd.className='msg them';",
  "      var cw=document.createElement('div');cw.className='who';cw.textContent=flavor.seatId||'';",
  "      cd.appendChild(cw);",
  "      cd.appendChild(document.createTextNode(flavor.text||''));",
  "      historyEl.appendChild(cd);",
  "    } else if(chatterStatus==='pending'){",
  "      var cp=document.createElement('div');cp.className='chatter';",
  "      cp.textContent=(flavor.fallback&&typeof flavor.fallback==='string')?flavor.fallback:'…';",
  "      historyEl.appendChild(cp);",
  "    } else if(chatterStatus==='failed'){",
  "      if(flavor.fallback&&typeof flavor.fallback==='string'){",
  "        var cf=document.createElement('div');cf.className='chatter';",
  "        cf.textContent=flavor.fallback;",
  "        historyEl.appendChild(cf);",
  "      }",
  "    }",
  "    atBottom();",
  "    // composer + finish availability",
  "    var canReply=hasAction(view,'reply');",
  "    sendBtn.disabled=!canReply;",
  "    inputEl.disabled=!canReply;",
  "    finishBtn.style.display=hasAction(view,'finish')?'block':'none';",
  "    resize();",
  "  }",
  "  function sendReply(){",
  "    var t=inputEl.value.trim();",
  "    if(!t||!xp) return;",
  "    xp.act('reply',{text:t});",
  "    inputEl.value='';",
  "  }",
  "  sendBtn.onclick=sendReply;",
  "  finishBtn.onclick=function(){ if(xp) xp.finish(); };",
  "  inputEl.addEventListener('keydown',function(e){ if(e.key==='Enter'&&!e.shiftKey){ e.preventDefault(); sendReply(); } });",
  "  xp=window.VibeExperience.connect(render,{",
  "    onPending:function(phase){",
  "      typingEl.style.display=phase==='typing'?'block':'none';",
  "      typingEl.textContent=phase==='typing'?'typing...':(phase==='effect'?'thinking...':'');",
  "    },",
  "    onError:function(err){var d=document.createElement('div');d.className='msg them';d.style.color='#f87171';d.textContent=err.message||err.code;historyEl.appendChild(d);atBottom();}",
  "  });",
  "})();",
  "</script>",
].join("\n");
