/**
 * Tetris realtime port (TETRIS_REALTIME_PORT_PLAN, TR-1..TR-3) — the user's
 * timer-mode mini-app «Тетрис» (`C:/Users/user/Downloads/Тетрис.vtapp.json`)
 * rewritten onto the realtime engine (REALTIME_EXPERIENCE_MODE_PLAN): fixed
 * `update(context, dt)` tick, input as `reduce` nudges without round-trips,
 * one commit at round end. Game logic is ported 1:1 (piece tables, colors,
 * spawn columns, dropSpeed 800→100ms, soft +1/hard +2 per cell, line table
 * [0,100,300,500,800]×level, level = floor(lines/10)+1, CW-only rotation,
 * no wall kick, top-out on blocked spawn).
 *
 * TR-2 addition (user quote, the source of truth): «я еще хочу, чтобы у него
 * была физика, когда блоки остаются без опоры, то они падают вниз» — cascade
 * physics. When a line clear leaves cells without support, they fall (one row
 * per tick, whole stacks together); after settling, full lines clear again
 * (chain reactions), each scored with the same table; the next piece spawns
 * only after the cascade fully resolves. Overhangs at normal lock do NOT
 * collapse — classic play stays 1:1; gravity wakes only when support
 * disappears.
 *
 * NOT a builtin: the app ships as a user `.vtapp.json` bundle (TR-4 assembles
 * it from these constants). Like `builtin-experiences.js`, this module is
 * deliberately NOT re-exported from the package barrel — the visual source is
 * a fat HTML blob whose literal `</script>` would break the generated frame
 * document. Import via the explicit subpath `@vibe-tavern/domain/tetris-port`.
 */

export const TETRIS_RULES_SOURCE = [
	"var PIECE_TYPES = [\"I\", \"O\", \"T\", \"S\", \"Z\", \"J\", \"L\"];",
	"var PIECES = {",
	"  I: [",
	"    [[0,0],[1,0],[2,0],[3,0]],",
	"    [[0,0],[0,1],[0,2],[0,3]],",
	"    [[0,0],[1,0],[2,0],[3,0]],",
	"    [[0,0],[0,1],[0,2],[0,3]]",
	"  ],",
	"  O: [",
	"    [[0,0],[1,0],[0,1],[1,1]],",
	"    [[0,0],[1,0],[0,1],[1,1]],",
	"    [[0,0],[1,0],[0,1],[1,1]],",
	"    [[0,0],[1,0],[0,1],[1,1]]",
	"  ],",
	"  T: [",
	"    [[1,0],[0,1],[1,1],[2,1]],",
	"    [[1,0],[1,1],[2,1],[1,2]],",
	"    [[0,0],[1,0],[2,0],[1,1]],",
	"    [[1,0],[0,1],[1,1],[1,2]]",
	"  ],",
	"  S: [",
	"    [[1,0],[2,0],[0,1],[1,1]],",
	"    [[0,0],[0,1],[1,1],[1,2]],",
	"    [[1,0],[2,0],[0,1],[1,1]],",
	"    [[0,0],[0,1],[1,1],[1,2]]",
	"  ],",
	"  Z: [",
	"    [[0,0],[1,0],[1,1],[2,1]],",
	"    [[1,0],[0,1],[1,1],[0,2]],",
	"    [[0,0],[1,0],[1,1],[2,1]],",
	"    [[1,0],[0,1],[1,1],[0,2]]",
	"  ],",
	"  J: [",
	"    [[0,0],[0,1],[1,1],[2,1]],",
	"    [[1,0],[2,0],[1,1],[1,2]],",
	"    [[0,0],[1,0],[2,0],[2,1]],",
	"    [[0,0],[0,1],[0,2],[1,2]]",
	"  ],",
	"  L: [",
	"    [[2,0],[0,1],[1,1],[2,1]],",
	"    [[1,0],[1,1],[1,2],[2,2]],",
	"    [[0,0],[1,0],[2,0],[0,1]],",
	"    [[0,0],[0,1],[1,1],[1,2]]",
	"  ]",
	"};",
	"",
	"var COLORS = {",
	"  I: \"#22d3ee\", O: \"#facc15\", T: \"#a855f7\",",
	"  S: \"#22c55e\", Z: \"#ef4444\", J: \"#3b82f6\", L: \"#f97316\"",
	"};",
	"",
	"var SPAWN_X = { I: 3, O: 4, T: 3, S: 3, Z: 3, J: 3, L: 3 };",
	"var WIDTH = 10;",
	"var HEIGHT = 20;",
	"var LINE_SCORE = [0, 100, 300, 500, 800];",
	"",
	"function emptyRow() {",
	"  var r = [];",
	"  for (var i = 0; i < WIDTH; i++) r.push(0);",
	"  return r;",
	"}",
	"",
	"function emptyGrid() {",
	"  var g = [];",
	"  for (var i = 0; i < HEIGHT; i++) g.push(emptyRow());",
	"  return g;",
	"}",
	"",
	"function dropSpeed(level) {",
	"  return Math.max(100, 800 - (level - 1) * 70);",
	"}",
	"",
	"function canPlace(grid, type, rotation, x, y) {",
	"  var cells = PIECES[type][rotation];",
	"  for (var i = 0; i < cells.length; i++) {",
	"    var cx = x + cells[i][0];",
	"    var cy = y + cells[i][1];",
	"    if (cx < 0 || cx >= WIDTH || cy >= HEIGHT) return false;",
	"    if (cy >= 0 && grid[cy][cx] !== 0) return false;",
	"  }",
	"  return true;",
	"}",
	"",
	"function canMove(grid, piece, dx, dy) {",
	"  return canPlace(grid, piece.type, piece.rotation, piece.x + dx, piece.y + dy);",
	"}",
	"",
	"function cloneGrid(grid) {",
	"  var g = [];",
	"  for (var i = 0; i < grid.length; i++) g.push(grid[i].slice());",
	"  return g;",
	"}",
	"",
	"function inscribe(grid, piece) {",
	"  var cells = PIECES[piece.type][piece.rotation];",
	"  for (var i = 0; i < cells.length; i++) {",
	"    var cx = piece.x + cells[i][0];",
	"    var cy = piece.y + cells[i][1];",
	"    if (cy >= 0 && cy < HEIGHT && cx >= 0 && cx < WIDTH) {",
	"      grid[cy][cx] = COLORS[piece.type];",
	"    }",
	"  }",
	"}",
	"",
	"function pieceOf(p, patch) {",
	"  var out = {};",
	"  for (var k in p) out[k] = p[k];",
	"  for (var k2 in patch) out[k2] = patch[k2];",
	"  return out;",
	"}",
	"",
	"function stateOf(s, patch) {",
	"  var out = {",
	"    grid: s.grid, current: s.current, next: s.next,",
	"    score: s.score, lines: s.lines, level: s.level,",
	"    fallAcc: s.fallAcc, cascade: s.cascade, lockPending: s.lockPending,",
	"    over: s.over",
	"  };",
	"  for (var k in patch) out[k] = patch[k];",
	"  return out;",
	"}",
	"",
	"function active(s) {",
	"  return { state: s, status: \"active\", events: [] };",
	"}",
	"",
	"function fullRowAt(grid, y) {",
	"  for (var x = 0; x < WIDTH; x++) {",
	"    if (grid[y][x] === 0) return false;",
	"  }",
	"  return true;",
	"}",
	"",
	"function collectFullRows(grid) {",
	"  var rows = [];",
	"  for (var y = 0; y < HEIGHT; y++) {",
	"    if (fullRowAt(grid, y)) rows.push(y);",
	"  }",
	"  return rows;",
	"}",
	"",
	"function clearRows(grid, rows) {",
	"  var keep = [];",
	"  for (var y = 0; y < HEIGHT; y++) {",
	"    if (rows.indexOf(y) === -1) keep.push(grid[y]);",
	"  }",
	"  var out = [];",
	"  for (var i = 0; i < rows.length; i++) out.push(emptyRow());",
	"  return out.concat(keep);",
	"}",
	"",
	"function hasFloaters(grid) {",
	"  for (var y = 0; y < HEIGHT - 1; y++) {",
	"    for (var x = 0; x < WIDTH; x++) {",
	"      if (grid[y][x] !== 0 && grid[y + 1][x] === 0) return true;",
	"    }",
	"  }",
	"  return false;",
	"}",
	"",
	"function fallOneRow(grid) {",
	"  // Bottom-up sweep: whole stacks shift together one row per tick (a",
	"  // top-down sweep would peel stacks apart cell by cell). One row per",
	"  // 50ms tick makes the cascade READ as falling, not teleporting.",
	"  var moved = false;",
	"  for (var y = HEIGHT - 2; y >= 0; y--) {",
	"    for (var x = 0; x < WIDTH; x++) {",
	"      if (grid[y][x] !== 0 && grid[y + 1][x] === 0) {",
	"        grid[y + 1][x] = grid[y][x];",
	"        grid[y][x] = 0;",
	"        moved = true;",
	"      }",
	"    }",
	"  }",
	"  return moved;",
	"}",
	"",
	"function clearedStats(s, cleared) {",
	"  var lines = s.lines + cleared;",
	"  return {",
	"    score: s.score + LINE_SCORE[cleared] * s.level,",
	"    lines: lines,",
	"    level: Math.floor(lines / 10) + 1",
	"  };",
	"}",
	"",
	"context.experience.register({",
	"  apiVersion: 1,",
	"  manifest: { id: \"tetris_arcade\", name: \"Тетрис\", mode: \"realtime\", tickMs: 50 },",
	"  capabilities: [",
	"    { capability: \"deterministic_random\", reason: \"random piece selection\" }",
	"  ],",
	"  create() {",
	"    // Grant-free create (Breakout parity): NO cursor draws here — create",
	"    // must succeed under EMPTY capability grants (the editor's rules",
	"    // validation and an ungranted session start inject no random; a draw",
	"    // here killed the imported app on 2026-08-21). The opening pieces are",
	"    // drawn by the FIRST update tick (spawnOpening) — the loop injects the",
	"    // cursor there unconditionally.",
	"    return {",
	"      grid: emptyGrid(),",
	"      current: null,",
	"      next: null,",
	"      score: 0,",
	"      lines: 0,",
	"      level: 1,",
	"      fallAcc: 0,",
	"      cascade: false,",
	"      lockPending: false,",
	"      over: false",
	"    };",
	"  },",
	"  project(context) {",
	"    var s = context.state;",
	"    var display = cloneGrid(s.grid);",
	"    if (s.current && !s.over) inscribe(display, s.current);",
	"    return {",
	"      grid: display,",
	"      score: s.score,",
	"      lines: s.lines,",
	"      level: s.level,",
	"      next: s.next,",
	"      gameOver: s.over",
	"    };",
	"  },",
	"  actions() {",
	"    // The five realtime nudges, type names 1:1 with the original app.",
	"    return [",
	"      { type: \"moveLeft\" },",
	"      { type: \"moveRight\" },",
	"      { type: \"rotate\" },",
	"      { type: \"softDrop\" },",
	"      { type: \"hardDrop\" }",
	"    ];",
	"  },",
	"  reduce(context, action) {",
	"    // Discrete shifts only. No locking, no clearing, and deliberately NO",
	"    // cursor draws (spawn lives in update — one place to verify on",
	"    // replay). Blocked soft/hard drops raise lockPending and the tick",
	"    // resolves the lock; every applied input resets fallAcc, mirroring",
	"    // the original withTimer() re-arm on every action.",
	"    var s = context.state;",
	"    if (s.over || !s.current || s.cascade) return active(s);",
	"    if (action.type === \"moveLeft\") {",
	"      if (canMove(s.grid, s.current, -1, 0)) {",
	"        return active(stateOf(s, { current: pieceOf(s.current, { x: s.current.x - 1 }), fallAcc: 0 }));",
	"      }",
	"      return active(stateOf(s, { fallAcc: 0 }));",
	"    }",
	"    if (action.type === \"moveRight\") {",
	"      if (canMove(s.grid, s.current, 1, 0)) {",
	"        return active(stateOf(s, { current: pieceOf(s.current, { x: s.current.x + 1 }), fallAcc: 0 }));",
	"      }",
	"      return active(stateOf(s, { fallAcc: 0 }));",
	"    }",
	"    if (action.type === \"rotate\") {",
	"      var newRot = (s.current.rotation + 1) % 4;",
	"      if (canPlace(s.grid, s.current.type, newRot, s.current.x, s.current.y)) {",
	"        return active(stateOf(s, { current: pieceOf(s.current, { rotation: newRot }), fallAcc: 0 }));",
	"      }",
	"      return active(stateOf(s, { fallAcc: 0 }));",
	"    }",
	"    if (action.type === \"softDrop\") {",
	"      if (canMove(s.grid, s.current, 0, 1)) {",
	"        return active(stateOf(s, { current: pieceOf(s.current, { y: s.current.y + 1 }), score: s.score + 1, fallAcc: 0 }));",
	"      }",
	"      return active(stateOf(s, { lockPending: true, fallAcc: 0 }));",
	"    }",
	"    if (action.type === \"hardDrop\") {",
	"      var dropY = 0;",
	"      while (canMove(s.grid, s.current, 0, dropY + 1)) { dropY++; }",
	"      return active(stateOf(s, {",
	"        current: pieceOf(s.current, { y: s.current.y + dropY }),",
	"        score: s.score + dropY * 2,",
	"        lockPending: true,",
	"        fallAcc: 0",
	"      }));",
	"    }",
	"    return active(s);",
	"  },",
	"  update(context, dt) {",
	"    // The realtime tick (dt is always the manifest tickMs). Phases:",
	"    // cascade (physics falling + chain clears) → opening draw (no piece",
	"    // yet) → lockPending (resolve a flagged lock) → gravity integration",
	"    // toward dropSpeed(level). The deterministic cursor is drawn ONLY",
	"    // here — create stays grant-free.",
	"    var s = context.state;",
	"    if (s.over) { return { state: s, status: \"completed\", events: [] }; }",
	"    if (s.cascade) return cascadeStep(s, context);",
	"    if (!s.current) return spawnOpening(s, context);",
	"    if (s.lockPending) return resolveLock(s, context);",
	"    var acc = s.fallAcc + dt;",
	"    var speed = dropSpeed(s.level);",
	"    if (acc < speed) return active(stateOf(s, { fallAcc: acc }));",
	"    if (canMove(s.grid, s.current, 0, 1)) {",
	"      return active(stateOf(s, { current: pieceOf(s.current, { y: s.current.y + 1 }), fallAcc: acc - speed }));",
	"    }",
	"    return resolveLock(stateOf(s, { fallAcc: 0 }), context);",
	"  }",
	"});",
	"",
	"function spawnOpening(s, context) {",
	"  // The round-opening draw (first piece + preview) runs in the FIRST",
	"  // update tick, never in create: create must succeed under EMPTY",
	"  // capability grants (the editor validation injects no cursor), while",
	"  // the realtime loop injects the cursor into every update tick.",
	"  var first = context.random.pick(PIECE_TYPES);",
	"  var second = context.random.pick(PIECE_TYPES);",
	"  return active(stateOf(s, { current: { type: first, rotation: 0, x: SPAWN_X[first], y: 0 }, next: second, fallAcc: 0 }));",
	"}",
	"",
	"function cascadeStep(s, context) {",
	"  // Physics phase: unsupported cells fall one row per tick; once",
	"  // settled, full rows clear again (chain — same score table), and only a",
	"  // fully stable board spawns the next piece. Input is ignored upstream",
	"  // (no current piece exists) and the cursor is never drawn here.",
	"  var grid = cloneGrid(s.grid);",
	"  if (fallOneRow(grid)) return active(stateOf(s, { grid: grid }));",
	"  var rows = collectFullRows(grid);",
	"  if (rows.length > 0) {",
	"    var st = clearedStats(s, rows.length);",
	"    return active(stateOf(s, {",
	"      grid: clearRows(grid, rows),",
	"      score: st.score,",
	"      lines: st.lines,",
	"      level: st.level",
	"    }));",
	"  }",
	"  return spawn(stateOf(s, { grid: grid, cascade: false }), context);",
	"}",
	"",
	"function resolveLock(s, context) {",
	"  // Lock the resting piece, score/clear full rows, then either enter",
	"  // the cascade (the clear left cells without support — the requested",
	"  // physics) or spawn immediately (classic lockAndSpawn parity).",
	"  var grid = cloneGrid(s.grid);",
	"  inscribe(grid, s.current);",
	"  var rows = collectFullRows(grid);",
	"  var st = rows.length > 0 ? clearedStats(s, rows.length) : { score: s.score, lines: s.lines, level: s.level };",
	"  if (rows.length > 0) grid = clearRows(grid, rows);",
	"  // Physics wakes ONLY when a clear removed support: overhangs above",
	"  // holes at a plain lock are classic play and must survive untouched.",
	"  if (rows.length > 0 && hasFloaters(grid)) {",
	"    return active(stateOf(s, { grid: grid, current: null, score: st.score, lines: st.lines, level: st.level, fallAcc: 0, cascade: true, lockPending: false }));",
	"  }",
	"  return spawn(stateOf(s, { grid: grid, current: null, score: st.score, lines: st.lines, level: st.level, fallAcc: 0, cascade: false, lockPending: false }), context);",
	"}",
	"",
	"function spawn(s, context) {",
	"  var type = s.next;",
	"  if (!canPlace(s.grid, type, 0, SPAWN_X[type], 0)) {",
	"    // Top-out: the round ends here; the projection carries the final",
	"    // board + score for the commit card.",
	"    return { state: stateOf(s, { over: true }), status: \"completed\", events: [] };",
	"  }",
	"  var nextType = context.random.pick(PIECE_TYPES);",
	"  return active(stateOf(s, {",
	"    current: { type: type, rotation: 0, x: SPAWN_X[type], y: 0 },",
	"    next: nextType,",
	"    fallAcc: 0,",
	"    cascade: false,",
	"    lockPending: false",
	"  }));",
	"}",
].join("\n");

export const TETRIS_VISUAL_SOURCE = [
	"<style>",
	"  * { margin: 0; padding: 0; box-sizing: border-box; }",
	"  body { background: #0f0f17; font-family: system-ui, -apple-system, sans-serif; color: #e5e5e5; }",
	"",
	"  .tetris-wrap {",
	"    display: flex;",
	"    gap: 16px;",
	"    padding: 16px;",
	"    min-width: 380px;",
	"    background: #0f0f17;",
	"  }",
	"",
	"  /* Play field */",
	"  .tetris-board {",
	"    position: relative;",
	"    width: 200px;",
	"    height: 400px;",
	"    background: #1a1a2e;",
	"    border: 2px solid #2a2a4a;",
	"    border-radius: 6px;",
	"    display: grid;",
	"    grid-template-columns: repeat(10, 1fr);",
	"    grid-template-rows: repeat(20, 1fr);",
	"    gap: 1px;",
	"    padding: 2px;",
	"  }",
	"  .tetris-cell {",
	"    background: #141428;",
	"    border-radius: 2px;",
	"  }",
	"  .tetris-cell.filled {",
	"    box-shadow: inset 0 0 0 1px rgba(255,255,255,0.25), inset 0 -2px 3px rgba(0,0,0,0.35);",
	"  }",
	"",
	"  /* Side panel */",
	"  .tetris-side {",
	"    display: flex;",
	"    flex-direction: column;",
	"    gap: 12px;",
	"    min-width: 130px;",
	"  }",
	"  .tetris-title {",
	"    font-size: 18px;",
	"    font-weight: 700;",
	"    letter-spacing: 1px;",
	"    color: #fff;",
	"    text-align: center;",
	"    padding-bottom: 4px;",
	"    border-bottom: 1px solid #2a2a4a;",
	"  }",
	"  .tetris-stat {",
	"    background: #1a1a2e;",
	"    border: 1px solid #2a2a4a;",
	"    border-radius: 6px;",
	"    padding: 8px 10px;",
	"    text-align: center;",
	"  }",
	"  .tetris-stat .label {",
	"    font-size: 10px;",
	"    text-transform: uppercase;",
	"    letter-spacing: 1px;",
	"    color: #888;",
	"    margin-bottom: 2px;",
	"  }",
	"  .tetris-stat .value {",
	"    font-size: 18px;",
	"    font-weight: 700;",
	"    color: #fff;",
	"  }",
	"",
	"  .tetris-next-box {",
	"    background: #1a1a2e;",
	"    border: 1px solid #2a2a4a;",
	"    border-radius: 6px;",
	"    padding: 8px;",
	"    text-align: center;",
	"  }",
	"  .tetris-next-box .label {",
	"    font-size: 10px;",
	"    text-transform: uppercase;",
	"    letter-spacing: 1px;",
	"    color: #888;",
	"    margin-bottom: 6px;",
	"  }",
	"  .tetris-next-grid {",
	"    display: grid;",
	"    grid-template-columns: repeat(4, 16px);",
	"    grid-template-rows: repeat(2, 16px);",
	"    gap: 1px;",
	"    justify-content: center;",
	"  }",
	"  .tetris-next-cell {",
	"    width: 16px;",
	"    height: 16px;",
	"    border-radius: 2px;",
	"    background: transparent;",
	"  }",
	"  .tetris-next-cell.filled {",
	"    box-shadow: inset 0 0 0 1px rgba(255,255,255,0.25), inset 0 -2px 3px rgba(0,0,0,0.35);",
	"  }",
	"",
	"  /* Controls */",
	"  .tetris-controls {",
	"    display: flex;",
	"    flex-direction: column;",
	"    gap: 6px;",
	"  }",
	"  .tetris-row {",
	"    display: flex;",
	"    gap: 6px;",
	"  }",
	"  .tetris-btn {",
	"    flex: 1;",
	"    background: #262644;",
	"    color: #e5e5e5;",
	"    border: 1px solid #3a3a5a;",
	"    border-radius: 6px;",
	"    padding: 10px 6px;",
	"    font-size: 12px;",
	"    font-weight: 600;",
	"    cursor: pointer;",
	"    text-align: center;",
	"    user-select: none;",
	"    transition: background 0.1s;",
	"  }",
	"  .tetris-btn:hover { background: #33335a; }",
	"  .tetris-btn:active { background: #2a2a50; transform: scale(0.96); }",
	"  .tetris-btn.primary {",
	"    background: #4f46e5;",
	"    border-color: #6366f1;",
	"    color: #fff;",
	"  }",
	"  .tetris-btn.primary:hover { background: #5b54f0; }",
	"  .tetris-btn.wide { width: 100%; }",
	"",
	"  /* Overlays */",
	"  .tetris-overlay {",
	"    position: absolute;",
	"    inset: 0;",
	"    background: rgba(10,10,20,0.88);",
	"    display: flex;",
	"    flex-direction: column;",
	"    align-items: center;",
	"    justify-content: center;",
	"    gap: 10px;",
	"    border-radius: 6px;",
	"    z-index: 10;",
	"  }",
	"  .tetris-overlay h2 {",
	"    font-size: 22px;",
	"    color: #fff;",
	"    text-align: center;",
	"  }",
	"  .tetris-overlay p {",
	"    font-size: 14px;",
	"    color: #aaa;",
	"    text-align: center;",
	"  }",
	"  .tetris-overlay .score-final {",
	"    font-size: 16px;",
	"    color: #facc15;",
	"    font-weight: 700;",
	"  }",
	"",
	"  .tetris-error {",
	"    font-size: 11px;",
	"    color: #f87171;",
	"    text-align: center;",
	"    padding: 4px;",
	"    white-space: pre-wrap;",
	"  }",
	"  .tetris-hint {",
	"    font-size: 10px;",
	"    color: #555;",
	"    text-align: center;",
	"    margin-top: 4px;",
	"  }",
	"</style>",
	"",
	"<div class=\"tetris-wrap\" id=\"xp-root\">",
	"  <div class=\"tetris-board\" id=\"board\">",
	"    <div class=\"tetris-overlay\" id=\"overlay\" style=\"display:none\">",
	"      <h2 id=\"overlay-title\">Tetris</h2>",
	"      <p id=\"overlay-text\"></p>",
	"    </div>",
	"  </div>",
	"",
	"  <div class=\"tetris-side\">",
	"    <div class=\"tetris-title\">TETRIS</div>",
	"",
	"    <div class=\"tetris-stat\">",
	"      <div class=\"label\">Score</div>",
	"      <div class=\"value\" id=\"stat-score\">0</div>",
	"    </div>",
	"    <div class=\"tetris-stat\">",
	"      <div class=\"label\">Lines</div>",
	"      <div class=\"value\" id=\"stat-lines\">0</div>",
	"    </div>",
	"    <div class=\"tetris-stat\">",
	"      <div class=\"label\">Level</div>",
	"      <div class=\"value\" id=\"stat-level\">1</div>",
	"    </div>",
	"",
	"    <div class=\"tetris-next-box\">",
	"      <div class=\"label\">Next</div>",
	"      <div class=\"tetris-next-grid\" id=\"next-grid\"></div>",
	"    </div>",
	"",
	"    <div class=\"tetris-controls\">",
	"      <div class=\"tetris-row\">",
	"        <button class=\"tetris-btn\" data-act=\"moveLeft\">← Влево</button>",
	"        <button class=\"tetris-btn\" data-act=\"moveRight\">Вправо →</button>",
	"      </div>",
	"      <div class=\"tetris-row\">",
	"        <button class=\"tetris-btn\" data-act=\"rotate\">↑ Поворот</button>",
	"        <button class=\"tetris-btn\" data-act=\"softDrop\">↓ Вниз</button>",
	"      </div>",
	"      <button class=\"tetris-btn wide\" data-act=\"hardDrop\">Сброс</button>",
	"      <button class=\"tetris-btn wide\" id=\"finish-btn\">Завершить раунд</button>",
	"    </div>",
	"",
	"    <div class=\"tetris-error\" id=\"error\" style=\"display:none\"></div>",
	"    <div class=\"tetris-hint\">← → двигать · ↑ поворот · ↓ мягко · пробел — сброс</div>",
	"  </div>",
	"</div>",
	"",
	"<script>",
	"(function () {",
	"  // Static rendering data for next-piece preview (display only, not game logic)",
	"  var PIECE_CELLS = {",
	"    I: [[0,0],[1,0],[2,0],[3,0]],",
	"    O: [[0,0],[1,0],[0,1],[1,1]],",
	"    T: [[1,0],[0,1],[1,1],[2,1]],",
	"    S: [[1,0],[2,0],[0,1],[1,1]],",
	"    Z: [[0,0],[1,0],[1,1],[2,1]],",
	"    J: [[0,0],[0,1],[1,1],[2,1]],",
	"    L: [[2,0],[0,1],[1,1],[2,1]]",
	"  };",
	"  var PIECE_COLORS = {",
	"    I: \"#22d3ee\", O: \"#facc15\", T: \"#a855f7\",",
	"    S: \"#22c55e\", Z: \"#ef4444\", J: \"#3b82f6\", L: \"#f97316\"",
	"  };",
	"",
	"  var root       = document.getElementById('xp-root');",
	"  var board      = document.getElementById('board');",
	"  var overlay    = document.getElementById('overlay');",
	"  var overlayTitle = document.getElementById('overlay-title');",
	"  var overlayText  = document.getElementById('overlay-text');",
	"  var scoreEl    = document.getElementById('stat-score');",
	"  var linesEl    = document.getElementById('stat-lines');",
	"  var levelEl    = document.getElementById('stat-level');",
	"  var nextGrid   = document.getElementById('next-grid');",
	"  var finishBtn  = document.getElementById('finish-btn');",
	"  var errorEl    = document.getElementById('error');",
	"",
	"  var xp = null;",
	"  var lastScore = 0;",
	"  var cellEls = [];",
	"",
	"  // Build 200 cells once",
	"  for (var i = 0; i < 200; i++) {",
	"    var c = document.createElement('div');",
	"    c.className = 'tetris-cell';",
	"    board.appendChild(c);",
	"    cellEls.push(c);",
	"  }",
	"",
	"  function resize() { if (xp) xp.resize(root.scrollWidth, root.scrollHeight); }",
	"",
	"  function sendInput(type) {",
	"    // actLocal is the frame-local realtime path (safe in a keydown handler",
	"    // — no round-trip, no one-action lock). Older turn-only hosts fall",
	"    // back to xp.act so the same visual hosts both modes.",
	"    if (!xp) return;",
	"    if (typeof xp.actLocal === 'function') { xp.actLocal(type); }",
	"    else if (typeof xp.act === 'function') { xp.act(type); }",
	"  }",
	"",
	"  function renderBoard(grid) {",
	"    for (var y = 0; y < 20; y++) {",
	"      for (var x = 0; x < 10; x++) {",
	"        var idx = y * 10 + x;",
	"        var val = grid[y][x];",
	"        if (val && val !== 0) {",
	"          cellEls[idx].style.background = val;",
	"          cellEls[idx].classList.add('filled');",
	"        } else {",
	"          cellEls[idx].style.background = '';",
	"          cellEls[idx].classList.remove('filled');",
	"        }",
	"      }",
	"    }",
	"  }",
	"",
	"  function renderNext(nextType) {",
	"    nextGrid.innerHTML = '';",
	"    var cells = {};",
	"    if (nextType && PIECE_CELLS[nextType]) {",
	"      var pcs = PIECE_CELLS[nextType];",
	"      for (var i = 0; i < pcs.length; i++) {",
	"        cells[pcs[i][0] + ',' + pcs[i][1]] = true;",
	"      }",
	"    }",
	"    for (var row = 0; row < 2; row++) {",
	"      for (var col = 0; col < 4; col++) {",
	"        var nc = document.createElement('div');",
	"        nc.className = 'tetris-next-cell';",
	"        if (cells[col + ',' + row]) {",
	"          nc.style.background = PIECE_COLORS[nextType] || '#fff';",
	"          nc.classList.add('filled');",
	"        }",
	"        nextGrid.appendChild(nc);",
	"      }",
	"    }",
	"  }",
	"",
	"  function showOverlay(title, text, extra) {",
	"    overlay.style.display = 'flex';",
	"    overlayTitle.textContent = title;",
	"    overlayText.textContent = text;",
	"    if (extra) {",
	"      var s = document.createElement('div');",
	"      s.className = 'score-final';",
	"      s.textContent = extra;",
	"      overlay.appendChild(s);",
	"    }",
	"  }",
	"",
	"  function hideOverlay() {",
	"    overlay.style.display = 'none';",
	"    var extras = overlay.querySelectorAll('.score-final');",
	"    for (var i = 0; i < extras.length; i++) extras[i].remove();",
	"  }",
	"",
	"  function renderView(view) {",
	"    if (!view) return;",
	"    // Dual-shape: realtime onTick delivers the FLAT project() return; a",
	"    // turn-mode host wraps it as {state:...}. Accept both.",
	"    var s = (view && view.state) || view || {};",
	"    errorEl.style.display = 'none';",
	"    if (typeof s.score === 'number') lastScore = s.score;",
	"    scoreEl.textContent = s.score != null ? s.score : 0;",
	"    linesEl.textContent = s.lines != null ? s.lines : 0;",
	"    levelEl.textContent = s.level != null ? s.level : 1;",
	"    renderNext(s.next);",
	"    if (s.grid) renderBoard(s.grid);",
	"    if (s.gameOver === true || view.status === 'completed') {",
	"      showOverlay('Game Over', 'Игра окончена', 'Score: ' + (s.score || 0));",
	"    } else {",
	"      hideOverlay();",
	"    }",
	"    resize();",
	"  }",
	"",
	"  function handleFinish(f) {",
	"    // Realtime terminal claim: the card renders from the FINAL state",
	"    // (top-out vs deliberate finish get distinct titles).",
	"    var fs = (f && f.finalState) || {};",
	"    if (fs.gameOver === true) {",
	"      showOverlay('Game Over', 'Игра окончена', 'Score: ' + (fs.score || 0));",
	"    } else {",
	"      showOverlay('Раунд завершён', 'Вы завершили раунд', 'Score: ' + (fs.score || 0));",
	"    }",
	"  }",
	"",
	"  function handleError(err) {",
	"    errorEl.textContent = (err && (err.message || err.kind)) || 'Ошибка';",
	"    errorEl.style.display = 'block';",
	"    resize();",
	"  }",
	"",
	"  // Static RU buttons — no rebuild from the actions list (the tick",
	"  // action is gone in realtime; the set is fixed).",
	"  var btns = document.querySelectorAll('[data-act]');",
	"  for (var b = 0; b < btns.length; b++) {",
	"    (function (btn) {",
	"      btn.onclick = function () { sendInput(btn.getAttribute('data-act')); };",
	"    })(btns[b]);",
	"  }",
	"",
	"  // Keyboard controls",
	"  document.addEventListener('keydown', function (e) {",
	"    var map = {",
	"      'ArrowLeft':  'moveLeft',",
	"      'ArrowRight': 'moveRight',",
	"      'ArrowUp':    'rotate',",
	"      'ArrowDown':  'softDrop',",
	"      ' ':          'hardDrop'",
	"    };",
	"    var type = map[e.key];",
	"    if (type) {",
	"      e.preventDefault();",
	"      sendInput(type);",
	"    }",
	"  });",
	"",
	"  finishBtn.onclick = function () {",
	"    // Deliberate end: score/summary ride the single commit.",
	"    if (xp && typeof xp.finishRound === 'function') {",
	"      xp.finishRound({ status: 'completed', score: lastScore, summary: 'Тетрис: ' + lastScore + ' очков' });",
	"    }",
	"  };",
	"",
	"  // onTick IS the frame (no requestAnimationFrame — the loop drives it).",
	"  xp = window.VibeExperience.connect(renderView, { onError: handleError });",
	"  if (xp.onTick) xp.onTick(renderView);",
	"  if (xp.onRoundFinish) xp.onRoundFinish(handleFinish);",
	"  if (xp.onRoundError) xp.onRoundError(handleError);",
	"})();",
	"</script>",
].join("\n");