#!/usr/bin/env python3
"""Regenerate the Vibe Tavern favicon + binary icon from the canonical logo.

Source of truth for the path data is
`apps/web/src/components/shared/vt-logo.ts` (BOOK_PATH + STAR_DEFS). The
colors are the coffee-theme accent tokens baked to sRGB (favicons / .ico
can't use CSS variables):
  --accent     oklch(0.72 0.14 75)   -> #D79628  (stars)
  --accent-mid oklch(0.55 0.105 75)  -> #95671C  (book)

Outputs (in apps/web/public/):
  logo.svg      square vt_sign mark, the raster source of truth
  logo-256.png  256x256 PNG favicon
  logo.ico      multi-resolution icon (256/128/64/48/32/16) for the binary

Usage:  python scripts/generate-logo-assets.py
Requires: Inkscape (on PATH or INKSCAPE env), Pillow.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "apps" / "web" / "public"

# --- Canonical paths (mirror apps/web/src/components/shared/vt-logo.ts) -------
BOOK_PATH = (
    "M228.277 60.5653L169.085 141.858L261.622 83.8188L269.364 96.163L176.183 "
    "154.606L281.244 126.197L285.047 140.264L159.958 174.088C158.598 165.58 "
    "151.226 159.078 142.334 159.078C133.476 159.078 126.127 165.53 124.726 "
    "173.99L0 140.264L3.80371 126.197L108.864 154.606L15.6831 96.163L23.4258 "
    "83.8188L115.962 141.858L56.7705 60.5653L68.5498 51.9882L142.523 153.582"
    "L216.498 51.9882L228.277 60.5653Z"
)
# Stars render at their absolute path coordinates (static rest pose).
STARS = [
    "M165.904 2.23722C166.998 -0.68871 171.137 -0.68873 172.23 2.23722L178.572 "
    "19.1986C178.86 19.9707 179.422 20.6109 180.149 20.998L192.127 27.3681"
    "C194.515 28.6384 194.515 32.0607 192.127 33.331L180.149 39.7011"
    "C179.422 40.0881 178.86 40.7283 178.572 41.5004L172.23 58.4618"
    "C171.137 61.3878 166.998 61.3878 165.904 58.4618L159.563 41.5004"
    "C159.274 40.7283 158.713 40.0881 157.985 39.7011L146.008 33.331"
    "C143.62 32.0607 143.62 28.6384 146.008 27.3681L157.985 20.998"
    "C158.713 20.6109 159.274 19.9707 159.563 19.1986L165.904 2.23722Z",
    "M122.963 49.1806C123.338 48.1762 124.759 48.1762 125.135 49.1806L129.501 "
    "60.8603C129.6 61.1253 129.793 61.3451 130.042 61.4779L138.271 65.8539"
    "C139.091 66.29 139.091 67.4652 138.271 67.9013L130.042 72.2777"
    "C129.793 72.4106 129.6 72.63 129.501 72.8949L125.135 84.5746"
    "C124.759 85.579 123.338 85.579 122.963 84.5746L118.597 72.8949"
    "C118.498 72.63 118.305 72.4106 118.055 72.2777L109.826 67.9013"
    "C109.006 67.4652 109.006 66.29 109.826 65.8539L118.055 61.4779"
    "C118.305 61.3451 118.498 61.1253 118.597 60.8603L122.963 49.1806Z",
    "M110.472 0.778726C110.86 -0.259575 112.329 -0.259575 112.717 0.778726"
    "L115.842 9.1381C115.945 9.41208 116.144 9.63943 116.402 9.77677"
    "L122.297 12.912C123.145 13.3628 123.145 14.5775 122.297 15.0282"
    "L116.402 18.164C116.144 18.3013 115.945 18.5282 115.842 18.8022"
    "L112.717 27.1615C112.329 28.1998 110.86 28.1998 110.472 27.1615"
    "L107.347 18.8022C107.244 18.5282 107.045 18.3013 106.787 18.164"
    "L100.891 15.0282C100.044 14.5775 100.044 13.3628 100.891 12.912"
    "L106.787 9.77677C107.045 9.63942 107.244 9.41209 107.347 9.1381"
    "L110.472 0.778726Z",
]

# Coffee-theme accent tokens baked to sRGB (see header comment).
ACCENT = "#D79628"      # stars  (--accent)
ACCENT_MID = "#95671C"  # book   (--accent-mid)

# The mark is 286x175 (landscape). Center it vertically in a 286x286 square so
# the icon fills the canvas width with even top/bottom padding.
MARK_W, MARK_H = 286, 175
SQUARE = 286
PAD_Y = (SQUARE - MARK_H) / 2  # 55.5
VIEWBOX = f"0 {-PAD_Y} {SQUARE} {SQUARE}"

ICO_SIZES = [256, 128, 64, 48, 32, 16]


def build_svg() -> str:
    stars = "\n".join(f'      <path d="{p}" fill="{ACCENT}"/>' for p in STARS)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Vibe Tavern icon source. GENERATED by scripts/generate-logo-assets.py.
     Path data mirrors apps/web/src/components/shared/vt-logo.ts; colors are the
     coffee-theme accent tokens baked to sRGB (icons can't use CSS variables).
     Do not edit by hand — re-run the generator. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEWBOX}" fill="none">
  <path d="{BOOK_PATH}" fill="{ACCENT_MID}"/>
{stars}
</svg>
"""


def find_inkscape() -> str:
    for name in ("inkscape", "inkscape.exe"):
        exe = shutil.which(name)
        if exe:
            return exe
    candidate = os.environ.get("INKSCAPE") or r"C:\Program Files\Inkscape\bin\inkscape.exe"
    if Path(candidate).exists():
        return candidate
    sys.exit("Inkscape not found. Install it or set INKSCAPE env var.")


def rasterize(inkscape: str, svg: Path, out: Path, size: int) -> None:
    subprocess.run(
        [inkscape, str(svg), "--export-type=png",
         f"--export-filename={out}", f"--export-width={size}", f"--export-height={size}"],
        check=True, capture_output=True,
    )


def main() -> None:
    PUBLIC.mkdir(parents=True, exist_ok=True)
    svg_text = build_svg()
    svg_path = PUBLIC / "logo.svg"
    svg_path.write_text(svg_text, encoding="utf-8")
    print(f"wrote {svg_path.relative_to(ROOT)}")

    inkscape = find_inkscape()
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        # 256x256 PNG favicon (also the largest ICO layer).
        png256 = PUBLIC / "logo-256.png"
        rasterize(inkscape, svg_path, png256, 256)
        print(f"wrote {png256.relative_to(ROOT)}")

        # Rasterize every ICO size, then assemble the multi-resolution .ico.
        layers = [Image.open(png256).convert("RGBA")]
        for size in ICO_SIZES[1:]:  # skip 256 (already have it)
            p = td / f"logo-{size}.png"
            rasterize(inkscape, svg_path, p, size)
            layers.append(Image.open(p).convert("RGBA"))
        ico_path = PUBLIC / "logo.ico"
        layers[0].save(ico_path, format="ICO", sizes=[(s, s) for s in ICO_SIZES])
        print(f"wrote {ico_path.relative_to(ROOT)} ({len(ICO_SIZES)} sizes)")

    # Sanity report.
    ico = Image.open(ico_path)
    print(f"\nlogo.ico sizes available: {sorted(s for s,_ in ico.info.get('sizes', []))}")


if __name__ == "__main__":
    main()
