#!/usr/bin/env python3
"""Regenerate the Vibe Tavern web and Android assets from the canonical logo.

Source of truth for the path data is read directly from
`apps/web/src/components/shared/vt-logo.ts` (BOOK_PATH + STAR_DEFS). The
colors are the coffee-theme accent tokens baked to sRGB (favicons / .ico
can't use CSS variables):
  --accent     oklch(0.72 0.14 75)   -> #D79628  (stars)
  --accent-mid oklch(0.55 0.105 75)  -> #95671C  (book)

Outputs:
  apps/web/public/logo.svg, logo-256.png, logo.ico
  mobile/android/.../drawable/vt_logo.xml
  mobile/android/.../drawable/ic_launcher_foreground.xml
  mobile/android/.../drawable/ic_launcher_background.xml
  mobile/android/.../font/inter_variable.ttf, alegreya_variable.ttf

Usage:  python scripts/generate-logo-assets.py
Requires: Inkscape (on PATH or INKSCAPE env), Pillow.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "apps" / "web" / "public"
ANDROID_RES = ROOT / "mobile" / "android" / "app" / "src" / "main" / "res"
ANDROID_DRAWABLE = ANDROID_RES / "drawable"
ANDROID_FONT = ANDROID_RES / "font"
WEB_FONT = PUBLIC / "fonts"

# --- Canonical paths (read from the TypeScript source of truth) ---------------
CANONICAL_LOGO = ROOT / "apps" / "web" / "src" / "components" / "shared" / "vt-logo.ts"


def load_canonical_paths() -> tuple[str, list[str]]:
    source = CANONICAL_LOGO.read_text(encoding="utf-8")
    book_match = re.search(r'export const BOOK_PATH\s*=\s*"([^"]+)";', source)
    stars = re.findall(r'path:\s*"([^"]+)"', source)
    if book_match is None or len(stars) != 3:
        raise RuntimeError(f"Could not read the canonical book and three stars from {CANONICAL_LOGO}")
    return book_match.group(1), stars


BOOK_PATH, STARS = load_canonical_paths()

# Coffee-theme accent tokens baked to sRGB (see header comment).
ACCENT = "#D79628"      # stars  (--accent)
ACCENT_MID = "#95671C"  # book   (--accent-mid)

# The mark is 286x175 (landscape). Center it vertically in a 286x286 square so
# the icon fills the canvas width with even top/bottom padding.
MARK_W, MARK_H = 286, 175
SQUARE = 286
PAD_Y = (SQUARE - MARK_H) / 2  # 55.5
VIEWBOX = f"0 {-PAD_Y} {SQUARE} {SQUARE}"

ICO_SIZES = [256, 128, 64, 48, 32, 16]


def build_svg() -> str:
    stars = "\n".join(f'      <path d="{p}" fill="{ACCENT}"/>' for p in STARS)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Vibe Tavern icon source. GENERATED by scripts/generate-logo-assets.py.
     Path data mirrors apps/web/src/components/shared/vt-logo.ts; colors are the
     coffee-theme accent tokens baked to sRGB (icons can't use CSS variables).
     Do not edit by hand — re-run the generator. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEWBOX}" fill="none">
  <path d="{BOOK_PATH}" fill="{ACCENT_MID}"/>
{stars}
</svg>
"""


def build_android_logo() -> str:
    stars = "\n".join(
        f'    <path android:fillColor="@color/vt_accent" android:pathData="{p}" />'
        for p in STARS
    )
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/generate-logo-assets.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="160dp"
    android:height="98dp"
    android:viewportWidth="286"
    android:viewportHeight="175">
    <path android:fillColor="@color/vt_accent_mid" android:pathData="{BOOK_PATH}" />
{stars}
</vector>
'''


def build_android_foreground() -> str:
    stars = "\n".join(
        f'        <path android:fillColor="@color/vt_accent" android:pathData="{p}" />'
        for p in STARS
    )
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/generate-logo-assets.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="468"
    android:viewportHeight="468">
    <!-- The 286x175 mark is centered in the adaptive-icon 66dp safe zone. -->
    <group android:translateX="91" android:translateY="146.5">
        <path android:fillColor="@color/vt_accent_mid" android:pathData="{BOOK_PATH}" />
{stars}
    </group>
</vector>
'''


def build_android_background() -> str:
    return '''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/generate-logo-assets.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:fillColor="@color/vt_background" android:pathData="M0,0h108v108H0z" />
</vector>
'''


def write_android_assets() -> None:
    ANDROID_DRAWABLE.mkdir(parents=True, exist_ok=True)
    outputs = {
        ANDROID_DRAWABLE / "vt_logo.xml": build_android_logo(),
        ANDROID_DRAWABLE / "ic_launcher_foreground.xml": build_android_foreground(),
        ANDROID_DRAWABLE / "ic_launcher_background.xml": build_android_background(),
    }
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")

    ANDROID_FONT.mkdir(parents=True, exist_ok=True)
    fonts = {
        WEB_FONT / "Inter-VariableFont_opsz,wght.ttf": ANDROID_FONT / "inter_variable.ttf",
        WEB_FONT / "Alegreya-VariableFont_wght.ttf": ANDROID_FONT / "alegreya_variable.ttf",
    }
    for source, destination in fonts.items():
        shutil.copyfile(source, destination)
        print(f"copied {source.relative_to(ROOT)} -> {destination.relative_to(ROOT)}")


def find_inkscape() -> str:
    for name in ("inkscape", "inkscape.exe"):
        exe = shutil.which(name)
        if exe:
            return exe
    candidate = os.environ.get("INKSCAPE") or r"C:\Program Files\Inkscape\bin\inkscape.exe"
    if Path(candidate).exists():
        return candidate
    sys.exit("Inkscape not found. Install it or set INKSCAPE env var.")


def rasterize(inkscape: str, svg: Path, out: Path, size: int) -> None:
    subprocess.run(
        [inkscape, str(svg), "--export-type=png",
         f"--export-filename={out}", f"--export-width={size}", f"--export-height={size}"],
        check=True, capture_output=True,
    )


def main() -> None:
    PUBLIC.mkdir(parents=True, exist_ok=True)
    write_android_assets()
    svg_text = build_svg()
    svg_path = PUBLIC / "logo.svg"
    svg_path.write_text(svg_text, encoding="utf-8")
    print(f"wrote {svg_path.relative_to(ROOT)}")

    inkscape = find_inkscape()
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        # 256x256 PNG favicon (also the largest ICO layer).
        png256 = PUBLIC / "logo-256.png"
        rasterize(inkscape, svg_path, png256, 256)
        print(f"wrote {png256.relative_to(ROOT)}")

        # Rasterize every ICO size, then assemble the multi-resolution .ico.
        layers = [Image.open(png256).convert("RGBA")]
        for size in ICO_SIZES[1:]:  # skip 256 (already have it)
            p = td / f"logo-{size}.png"
            rasterize(inkscape, svg_path, p, size)
            layers.append(Image.open(p).convert("RGBA"))
        ico_path = PUBLIC / "logo.ico"
        layers[0].save(ico_path, format="ICO", sizes=[(s, s) for s in ICO_SIZES])
        print(f"wrote {ico_path.relative_to(ROOT)} ({len(ICO_SIZES)} sizes)")

    # Sanity report.
    ico = Image.open(ico_path)
    print(f"\nlogo.ico sizes available: {sorted(s for s,_ in ico.info.get('sizes', []))}")


if __name__ == "__main__":
    main()
