/**
 * Generates `services/api/src/server/embedded-web-manifest.ts` — a map of
 * URL pathname → embedded-file path that bakes the entire built frontend
 * (out/apps/web/**) into the standalone .exe via Bun's
 * `import ... with { type: "file" }` mechanism.
 *
 * Why this exists: a user extracting only `vibe-tavern.exe` (or an antivirus
 * quarantining a single JS chunk) ended up with a missing `web/assets/`
 * directory and a permanently frozen splash screen — the browser refused to
 * execute the SPA bundle it couldn't fetch, and the failure was completely
 * silent. Embedding the frontend inside the executable makes that failure
 * mode impossible: either the whole .exe is missing (loud) or it's all there.
 *
 * Lifecycle:
 *   - In dev / typecheck / `bun run dev`, the manifest on disk is the empty
 *     stub (empty map) committed to git. The server then serves web/ from
 *     disk via hono serveStatic, exactly as before.
 *   - During `bun run build:standalone`, build-standalone.ts calls
 *     `generateEmbeddedWebManifest()` BEFORE the Bun.build compile step (so
 *     the bundler sees the real imports and embeds the bytes), then calls
 *     `writeEmbeddedWebStub()` in a `finally` to restore the stub — leaving
 *     the working tree clean and dev behaviour unaffected.
 *
 * Direct usage (manual / recovery):
 *   bun scripts/generate-embedded-web-manifest.ts           # generate full
 *   bun scripts/generate-embedded-web-manifest.ts --stub    # restore stub
 */

import { dirname, join, relative, resolve, sep } from "node:path";
import { readdir, writeFile } from "node:fs/promises";

const ROOT = resolve(import.meta.dir, "..");
const WEB_SOURCE = join(ROOT, "out", "apps", "web");

/** Absolute path to the generated/stub manifest file. */
export const MANIFEST_PATH = join(ROOT, "services", "api", "src", "server", "embedded-web-manifest.ts");

/** The empty stub committed to git. Restored after every standalone build. */
export const STUB_CONTENT = `// AUTO-GENERATED stub. Replaced by scripts/generate-embedded-web-manifest.ts
// during \`bun run build:standalone\`, then restored to this stub afterward.
//
// In dev and \`bun run dev\`, this empty map means the frontend is served from
// the on-disk web/ directory via hono serveStatic. In the compiled standalone
// executable, the build script regenerates this file with real
// \`import ... with { type: "file" }\` entries embedding every file under
// out/apps/web/ — so the .exe is fully self-contained and no external web/
// folder is required. This eliminates the "frozen splash" failure mode where
// a user extracts only the .exe (or an antivirus quarantines a single JS
// chunk) and the browser can't load the SPA bundle.
//
// Map shape: URL pathname (e.g. "/assets/index-Abc.js") → embedded file path
// (an opaque "$bunfs/..." or "B:/~BUN/root/..." string returned by the
// \`with { type: "file" }\` import). Served verbatim in app-factory.ts.

export const embeddedWebFiles: Record<string, string> = {};
`;

async function scanFiles(dir: string): Promise<string[]> {
	const out: string[] = [];
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) {
			out.push(...await scanFiles(full));
		} else if (entry.isFile()) {
			out.push(full);
		}
	}
	return out;
}

/** Rewrites the manifest with real embed-imports for every file under WEB_SOURCE. */
export async function generateEmbeddedWebManifest(): Promise<{ fileCount: number }> {
	const files = (await scanFiles(WEB_SOURCE)).sort();
	if (files.length === 0) {
		throw new Error(
			`No files found in ${WEB_SOURCE}. Run the frontend build (bun run build) first.`,
		);
	}

	// URL pathname = path relative to web/, forward-slashed, leading "/".
	// Import path   = path relative to the manifest file's directory, forward-slashed.
	const manifestDir = dirname(MANIFEST_PATH);
	const importLines: string[] = [];
	const mapEntries: string[] = [];

	files.forEach((absPath, i) => {
		const urlPath = "/" + relative(WEB_SOURCE, absPath).split(sep).join("/");
		// Bun import specifiers use forward slashes on all platforms.
		const importPath = relative(manifestDir, absPath).split(sep).join("/");
		const ident = `f${i}`;
		importLines.push(`import ${ident} from "${importPath}" with { type: "file" };`);
		mapEntries.push(`\t${JSON.stringify(urlPath)}: ${ident},`);
	});

	const content = `// AUTO-GENERATED by scripts/generate-embedded-web-manifest.ts — DO NOT EDIT.
// Restored to the empty stub by build-standalone.ts after each compile.
//
// Embeds every file under out/apps/web/ into the standalone .exe via Bun's
// \`import ... with { type: "file" }\` mechanism. At compile time Bun reads
// each file, stores its bytes inside the executable, and rewrites the import
// to an opaque internal path (\`$bunfs/...\` or \`B:/~BUN/root/...\`). At runtime
// the server resolves incoming URL pathnames through \`embeddedWebFiles\`
// (see app-factory.ts) and serves the embedded blob with the correct MIME —
// no on-disk web/ folder required.
//
// In dev this file is the empty stub (see git), so the map is empty and the
// server falls back to serving web/ from disk via hono serveStatic.

${importLines.join("\n")}

export const embeddedWebFiles: Record<string, string> = {
${mapEntries.join("\n")}
};
`;

	await writeFile(MANIFEST_PATH, content, "utf-8");
	console.log(
		`[generate-embedded-web-manifest] Embedded ${files.length} file(s) into services/api/src/server/embedded-web-manifest.ts`,
	);
	return { fileCount: files.length };
}

/** Restores the empty stub. Called in build-standalone.ts `finally`. */
export async function writeEmbeddedWebStub(): Promise<void> {
	await writeFile(MANIFEST_PATH, STUB_CONTENT, "utf-8");
	console.log("[generate-embedded-web-manifest] Restored embedded-web-manifest.ts stub.");
}

async function main(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.includes("--stub")) {
		await writeEmbeddedWebStub();
		return;
	}
	await generateEmbeddedWebManifest();
}

if (import.meta.main) {
	main().catch((err) => {
		console.error("[generate-embedded-web-manifest] Failed:", err);
		process.exit(1);
	});
}
