import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { embedCharaMetadata } from "../../apps/web/src/lib/png-writer.ts";

const OUT_DIR = "N:/mock-user";
const NUM_CHARACTERS = 1000;
const CHATS_PER_CHAR = 10;
const MESSAGES_PER_CHAT = 100;
const NUM_LOREBOOKS = 50;
const NUM_PRESETS = 50;
const NUM_PERSONAS = 50;

// Minimal 1x1 transparent PNG
const BASE_PNG_B64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==";

async function generateMockData() {
  console.log(`Generating mock data in ${OUT_DIR}...`);
  console.log(`Characters: ${NUM_CHARACTERS}`);
  console.log(`Chats: ${NUM_CHARACTERS * CHATS_PER_CHAR}`);
  console.log(`Messages: ${NUM_CHARACTERS * CHATS_PER_CHAR * MESSAGES_PER_CHAT}`);

  await mkdir(join(OUT_DIR, "characters"), { recursive: true });
  await mkdir(join(OUT_DIR, "chats"), { recursive: true });
  await mkdir(join(OUT_DIR, "worlds"), { recursive: true });
  await mkdir(join(OUT_DIR, "OpenAI Settings"), { recursive: true });

  const charsDir = join(OUT_DIR, "characters");
  const chatsDir = join(OUT_DIR, "chats");

  const basePngBytes = Uint8Array.from(atob(BASE_PNG_B64), c => c.charCodeAt(0));

  for (let i = 1; i <= NUM_CHARACTERS; i++) {
    const charName = `MockBot_${i}`;

    const cardData = {
      spec: "chara_card_v2",
      spec_version: "2.0",
      data: {
        name: charName,
        description: `This is a mock character for stress testing. ID: ${i}`,
        personality: "Helpful, robotic, mock",
        scenario: "Stress testing the Vibe Tavern import system.",
        first_mes: `Hello! I am ${charName}. Let's test the import!`,
        mes_example: "{{user}}: Hi\n{{char}}: Hello!",
        creator_notes: "Generated by mock script",
        system_prompt: "You are a mock bot.",
        post_history_instructions: "",
        tags: ["mock", "stress-test"],
        creator: "Bench Script",
        character_version: "1.0",
        alternate_greetings: ["Alt greeting 1", "Alt greeting 2"],
      },
    };

    // Embed into PNG instead of saving as JSON
    const finalPng = embedCharaMetadata(basePngBytes, JSON.stringify(cardData));
    await writeFile(join(charsDir, `${charName}.png`), finalPng);

    const charChatsDir = join(chatsDir, charName);
    await mkdir(charChatsDir, { recursive: true });

    for (let c = 1; c <= CHATS_PER_CHAR; c++) {
      const lines: string[] = [];
      const chatId = `chat_${Date.now()}_${i}_${c}`;

      lines.push(
        JSON.stringify({
          user_name: "MockUser",
          character_name: charName,
          chat_metadata: { created: Date.now() },
        })
      );

      let timestamp = Date.now() - 10000000;
      for (let m = 1; m <= MESSAGES_PER_CHAT; m++) {
        const isUser = m % 2 === 0;
        const msg = {
          name: isUser ? "MockUser" : charName,
          is_user: isUser,
          is_system: false,
          mes: isUser
            ? `Message ${m} from user.`
            : `Message ${m} from ${charName}. This is dummy content to pad out the JSONL size and simulate a real chat log.`,
          send_date: timestamp,
          swipes: isUser ? undefined : [`Message ${m} from ${charName}. This is dummy content to pad out the JSONL size and simulate a real chat log.`],
          swipe_id: isUser ? undefined : 0,
        };
        lines.push(JSON.stringify(msg));
        timestamp += 60000;
      }

      await writeFile(join(charChatsDir, `${chatId}.jsonl`), lines.join("\n"), "utf8");
    }

    if (i % 100 === 0) console.log(`Generated ${i}/${NUM_CHARACTERS} characters...`);
  }

  // 2. Lorebooks (worlds)
  const worldsDir = join(OUT_DIR, "worlds");
  for (let i = 1; i <= NUM_LOREBOOKS; i++) {
    const lore = {
      name: `Mock Lorebook ${i}`,
      entries: {
        "1": {
          uid: 1,
          key: ["test", `mock_${i}`],
          keysecondary: [],
          content: `Mock content for lorebook ${i}`,
          constant: false,
        }
      }
    };
    await writeFile(join(worldsDir, `Mock_Lorebook_${i}.json`), JSON.stringify(lore, null, 2), "utf8");
  }
  console.log(`Generated ${NUM_LOREBOOKS} lorebooks.`);

  // 3. Presets (OpenAI Settings)
  const presetsDir = join(OUT_DIR, "OpenAI Settings");
  for (let i = 1; i <= NUM_PRESETS; i++) {
    const preset = {
      name: `Mock Preset ${i}`,
      prompts: [
        { identifier: "main", name: "Main", content: "You are a mock AI.", role: "system" }
      ]
    };
    await writeFile(join(presetsDir, `Mock_Preset_${i}.json`), JSON.stringify(preset, null, 2), "utf8");
  }
  console.log(`Generated ${NUM_PRESETS} presets.`);

  // 4. Personas (settings.json)
  const personasData: Record<string, string> = {};
  const personasDescs: Record<string, { description: string }> = {};
  for (let i = 1; i <= NUM_PERSONAS; i++) {
    const key = `persona_${i}.png`;
    personasData[key] = `Mock Persona ${i}`;
    personasDescs[key] = {
      description: `Description for persona ${i}`,
    };
  }
  await writeFile(
    join(OUT_DIR, "settings.json"),
    JSON.stringify({ personas: personasData, persona_descriptions: personasDescs }, null, 2),
    "utf8"
  );
  console.log(`Generated ${NUM_PERSONAS} personas.`);

  console.log("Done! Mock data generated.");
}

generateMockData().catch(console.error);
